CREATE TABLE "PCBCRP"."CFG_FXVIGENTE" 
   (	"ID" VARCHAR2(255 BYTE), 
	"SUBPRODUCTO" VARCHAR2(10 BYTE), 
	"OPERACION" VARCHAR2(10 BYTE), 
	"FECHA_VENCIMIENTO" VARCHAR2(20 BYTE), 
	"DIVISA" VARCHAR2(15 BYTE), 
	"CUENTA" VARCHAR2(50 BYTE), 
	"CODIGOESTADO" NUMBER(10,0) NOT NULL ENABLE, 
	"ACTUALIZADO_POR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CREADO_POR" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"FECHA_CREACION" TIMESTAMP (6) NOT NULL ENABLE, 
	"FECHA_MODIFICACION" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "CFG_FXVIGENTE_PK" PRIMARY KEY ("ID")
   );




 GRANT UPDATE,SELECT,INSERT,DELETE ON "PCBCRP"."CFG_FXVIGENTE" TO "APP_PCBCRP";


--------------------------------------------------------
--  DDL for Table QRTZ_BLOB_TRIGGERS
--------------------------------------------------------

CREATE TABLE "PCBCRP"."QRTZ_BLOB_TRIGGERS" (	
	"SCHED_NAME" VARCHAR2(120 BYTE), 
	"TRIGGER_NAME" VARCHAR2(200 BYTE), 
	"TRIGGER_GROUP" VARCHAR2(200 BYTE), 
	"BLOB_DATA" BLOB
)  ;
--------------------------------------------------------
--  DDL for Table QRTZ_CALENDARS
--------------------------------------------------------

CREATE TABLE "PCBCRP"."QRTZ_CALENDARS" (	
	"SCHED_NAME" VARCHAR2(120 BYTE), 
	"CALENDAR_NAME" VARCHAR2(200 BYTE), 
	"CALENDAR" BLOB
) ;
--------------------------------------------------------
--  DDL for Table QRTZ_CRON_TRIGGERS
--------------------------------------------------------

CREATE TABLE "PCBCRP"."QRTZ_CRON_TRIGGERS" (	
	"SCHED_NAME" VARCHAR2(120 BYTE), 
	"TRIGGER_NAME" VARCHAR2(200 BYTE), 
	"TRIGGER_GROUP" VARCHAR2(200 BYTE), 
	"CRON_EXPRESSION" VARCHAR2(120 BYTE), 
	"TIME_ZONE_ID" VARCHAR2(80 BYTE)
) ;
--------------------------------------------------------
--  DDL for Table QRTZ_FIRED_TRIGGERS
--------------------------------------------------------

CREATE TABLE "PCBCRP"."QRTZ_FIRED_TRIGGERS" (	
	"SCHED_NAME" VARCHAR2(120 BYTE), 
	"ENTRY_ID" VARCHAR2(95 BYTE), 
	"TRIGGER_NAME" VARCHAR2(200 BYTE), 
	"TRIGGER_GROUP" VARCHAR2(200 BYTE), 
	"INSTANCE_NAME" VARCHAR2(200 BYTE), 
	"FIRED_TIME" NUMBER(13,0), 
	"SCHED_TIME" NUMBER(13,0), 
	"PRIORITY" NUMBER(13,0), 
	"STATE" VARCHAR2(16 BYTE), 
	"JOB_NAME" VARCHAR2(200 BYTE), 
	"JOB_GROUP" VARCHAR2(200 BYTE), 
	"IS_NONCONCURRENT" VARCHAR2(1 BYTE), 
	"REQUESTS_RECOVERY" VARCHAR2(1 BYTE)
)  ;
--------------------------------------------------------
--  DDL for Table QRTZ_JOB_DETAILS
--------------------------------------------------------

CREATE TABLE "PCBCRP"."QRTZ_JOB_DETAILS" (	
	"SCHED_NAME" VARCHAR2(120 BYTE), 
	"JOB_NAME" VARCHAR2(200 BYTE), 
	"JOB_GROUP" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"JOB_CLASS_NAME" VARCHAR2(250 BYTE), 
	"IS_DURABLE" VARCHAR2(1 BYTE), 
	"IS_NONCONCURRENT" VARCHAR2(1 BYTE), 
	"IS_UPDATE_DATA" VARCHAR2(1 BYTE), 
	"REQUESTS_RECOVERY" VARCHAR2(1 BYTE), 
	"JOB_DATA" BLOB
) ;
--------------------------------------------------------
--  DDL for Table QRTZ_LOCKS
--------------------------------------------------------

CREATE TABLE "PCBCRP"."QRTZ_LOCKS" (	
	"SCHED_NAME" VARCHAR2(120 BYTE), 
	"LOCK_NAME" VARCHAR2(40 BYTE)
) ;
--------------------------------------------------------
--  DDL for Table QRTZ_PAUSED_TRIGGER_GRPS
--------------------------------------------------------

CREATE TABLE "PCBCRP"."QRTZ_PAUSED_TRIGGER_GRPS" (	
	"SCHED_NAME" VARCHAR2(120 BYTE), 
	"TRIGGER_GROUP" VARCHAR2(200 BYTE)
)  ;
--------------------------------------------------------
--  DDL for Table QRTZ_SCHEDULER_STATE
--------------------------------------------------------

CREATE TABLE "PCBCRP"."QRTZ_SCHEDULER_STATE" (	
	"SCHED_NAME" VARCHAR2(120 BYTE), 
	"INSTANCE_NAME" VARCHAR2(200 BYTE), 
	"LAST_CHECKIN_TIME" NUMBER(13,0), 
	"CHECKIN_INTERVAL" NUMBER(13,0)
)  ;
--------------------------------------------------------
--  DDL for Table QRTZ_SIMPLE_TRIGGERS
--------------------------------------------------------

CREATE TABLE "PCBCRP"."QRTZ_SIMPLE_TRIGGERS" (	
	"SCHED_NAME" VARCHAR2(120 BYTE), 
	"TRIGGER_NAME" VARCHAR2(200 BYTE), 
	"TRIGGER_GROUP" VARCHAR2(200 BYTE), 
	"REPEAT_COUNT" NUMBER(7,0), 
	"REPEAT_INTERVAL" NUMBER(12,0), 
	"TIMES_TRIGGERED" NUMBER(10,0)
)  ;
--------------------------------------------------------
--  DDL for Table QRTZ_SIMPROP_TRIGGERS
--------------------------------------------------------

CREATE TABLE "PCBCRP"."QRTZ_SIMPROP_TRIGGERS" (	
	"SCHED_NAME" VARCHAR2(120 BYTE), 
	"TRIGGER_NAME" VARCHAR2(200 BYTE), 
	"TRIGGER_GROUP" VARCHAR2(200 BYTE), 
	"STR_PROP_1" VARCHAR2(512 BYTE), 
	"STR_PROP_2" VARCHAR2(512 BYTE), 
	"STR_PROP_3" VARCHAR2(512 BYTE), 
	"INT_PROP_1" NUMBER(10,0), 
	"INT_PROP_2" NUMBER(10,0), 
	"LONG_PROP_1" NUMBER(13,0), 
	"LONG_PROP_2" NUMBER(13,0), 
	"DEC_PROP_1" NUMBER(13,4), 
	"DEC_PROP_2" NUMBER(13,4), 
	"BOOL_PROP_1" VARCHAR2(1 BYTE), 
	"BOOL_PROP_2" VARCHAR2(1 BYTE)
)  ;
--------------------------------------------------------
--  DDL for Table QRTZ_TRIGGERS
--------------------------------------------------------

CREATE TABLE "PCBCRP"."QRTZ_TRIGGERS" (	
	"SCHED_NAME" VARCHAR2(120 BYTE), 
	"TRIGGER_NAME" VARCHAR2(200 BYTE), 
	"TRIGGER_GROUP" VARCHAR2(200 BYTE), 
	"JOB_NAME" VARCHAR2(200 BYTE), 
	"JOB_GROUP" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"NEXT_FIRE_TIME" NUMBER(13,0), 
	"PREV_FIRE_TIME" NUMBER(13,0), 
	"PRIORITY" NUMBER(13,0), 
	"TRIGGER_STATE" VARCHAR2(16 BYTE), 
	"TRIGGER_TYPE" VARCHAR2(8 BYTE), 
	"START_TIME" NUMBER(13,0), 
	"END_TIME" NUMBER(13,0), 
	"CALENDAR_NAME" VARCHAR2(200 BYTE), 
	"MISFIRE_INSTR" NUMBER(2,0), 
	"JOB_DATA" BLOB
)  ;


--------------------------------------------------------
--  DDL for Table CODIGO_STAR_ALTAMIRA
--------------------------------------------------------

CREATE TABLE "PCBCRP"."CODIGO_STAR_ALTAMIRA"(	
	"ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ACTUALIZADO_POR" VARCHAR2(255 CHAR), 
	"CODIGOESTADO" NUMBER(10,0), 
	"CREADO_POR" VARCHAR2(255 CHAR), 
	"FECHA_CREACION" TIMESTAMP (6), 
	"FECHA_MODIFICACION" TIMESTAMP (6), 
	"ALTAMIRA" VARCHAR2(20 CHAR), 
	"CODIGO" VARCHAR2(20 CHAR), 
	PRIMARY KEY ("ID")
) ;

GRANT SELECT, INSERT, UPDATE, DELETE ON "PCBCRP"."QRTZ_BLOB_TRIGGERS" TO "APP_PCBCRP"; 
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCBCRP"."QRTZ_CALENDARS" TO "APP_PCBCRP"; 
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCBCRP"."QRTZ_CRON_TRIGGERS" TO "APP_PCBCRP"; 
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCBCRP"."QRTZ_FIRED_TRIGGERS" TO "APP_PCBCRP"; 
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCBCRP"."QRTZ_JOB_DETAILS" TO "APP_PCBCRP"; 
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCBCRP"."QRTZ_LOCKS" TO "APP_PCBCRP"; 
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCBCRP"."QRTZ_PAUSED_TRIGGER_GRPS" TO "APP_PCBCRP"; 
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCBCRP"."QRTZ_SCHEDULER_STATE" TO "APP_PCBCRP"; 
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCBCRP"."QRTZ_SIMPLE_TRIGGERS" TO "APP_PCBCRP"; 
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCBCRP"."QRTZ_SIMPROP_TRIGGERS" TO "APP_PCBCRP"; 
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCBCRP"."QRTZ_TRIGGERS" TO "APP_PCBCRP";
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCBCRP"."CODIGO_STAR_ALTAMIRA"  TO "APP_PCBCRP";