-- INICIO CPASCOS

--------------------------------------------------------
--  DELETE STORED PROCEDURES
--------------------------------------------------------
DROP PROCEDURE "PCBCRP"."SP_BCR_CLIENTE_LISTAR";

--------------------------------------------------------
--  DDL for Procedure SP_BCR_CLIENTE_LISTAR
--------------------------------------------------------

create PROCEDURE "PCBCRP"."SP_BCR_CLIENTE_LISTAR" (
P_CODIGO 				IN VARCHAR2,
P_NOMBRE         		IN VARCHAR2,
P_TIPOCLIENTE          	IN VARCHAR2,
P_CLIENTENOREGISTRADO   IN VARCHAR2,
CURSOR_ 				OUT SYS_REFCURSOR
)
AS

BEGIN
   IF P_CLIENTENOREGISTRADO <> 'S' THEN
        OPEN CURSOR_ FOR
		SELECT 
			cli.ID,         
			cli.CODIGO,
			cli.NOMBRE,
			cli.ENTIDAD,
			cli.PAISRESIDENCIA AS PAISRESIDENCIA,
			pr.DESCRIPCION AS PAISRESIDENCIADESC,
			cli.RIESGOPAIS AS RIESGOPAIS,
			rp.DESCRIPCION AS RIESGOPAISDESC,
			cli.ALTAMIRA,
			cli.PLAZA,
			RTRIM(LTRIM(cli.SECTOR)) AS SECTOR,
			cli.NOMBRECORTO,
			cli.RECHAZARCARGA AS RECHAZARCARGA,
			cc.DESCRIPCION AS RECHAZARCARGADESC,
			cli.TIPOCLIENTE AS TIPOCLIENTE,
			tc.DESCRIPCION AS TIPOCLIENTEDESC,
			cli.TIPODOCUMENTO AS TIPODOCUMENTO,
			td.DESCRIPCION AS TIPODOCUMENTODESC,
			cli.NUMERODOCUMENTO,
			cli.CODIGOSWIFT,
			cli.CODIGOESTADO
		FROM 
			CLIENTE cli
				LEFT JOIN (SELECT 
								det.DESCRIPCION, 
								val.VALOR 
							FROM 
								PARAMETRO par 
									INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO 
									INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '007') pr ON cli.PAISRESIDENCIA = pr.VALOR --Tipo Pais

				LEFT JOIN (SELECT 
								det.DESCRIPCION, 
								val.VALOR 
							FROM 
								PARAMETRO par 
									INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO 
									INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '007') rp ON cli.RIESGOPAIS = rp.VALOR --Tipo Pais

				LEFT JOIN (SELECT 
								det.DESCRIPCION, 
								val.VALOR 
							FROM 
								PARAMETRO par 
									INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO 
									INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '009') cc ON cli.RECHAZARCARGA = cc.VALOR --Carga Cliente

				LEFT JOIN (SELECT 
								det.DESCRIPCION, 
								val.VALOR 
							FROM 
								PARAMETRO par 
									INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO 
									INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '004') tc ON cli.TIPOCLIENTE = tc.VALOR --Tipo Cliente  
				LEFT JOIN (SELECT 
								det.DESCRIPCION, 
								val.VALOR 
							FROM 
								PARAMETRO par 
									INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO 
									INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '040') td ON cli.TIPODOCUMENTO = td.VALOR --Tipo Documento 
		WHERE 
			cli.CODIGOESTADO = 1 
			AND cli.CODIGO LIKE '%' || NVL(P_CODIGO,'') || '%' 
            AND UPPER(cli.NOMBRE) LIKE '%' || UPPER(NVL(P_NOMBRE,'')) || '%' 
			AND cli.TIPOCLIENTE = 
                CASE 
                    WHEN P_TIPOCLIENTE = '-2' THEN cli.TIPOCLIENTE 
                    ELSE P_TIPOCLIENTE 
                END;

	ELSE
        OPEN CURSOR_ FOR
		SELECT 
			cli.ID,         
			cli.CODIGO,
			cli.NOMBRE,
			cli.ENTIDAD,
			cli.PAISRESIDENCIA AS PAISRESIDENCIA,
			pr.DESCRIPCION AS PAISRESIDENCIADESC,
			cli.RIESGOPAIS AS RIESGOPAIS,
			rp.DESCRIPCION AS RIESGOPAISDESC,
			cli.ALTAMIRA,
			cli.PLAZA,
			RTRIM(LTRIM(cli.SECTOR)) AS SECTOR,
			cli.NOMBRECORTO,
			cli.RECHAZARCARGA AS RECHAZARCARGA,
			cc.DESCRIPCION AS RECHAZARCARGADESC,
			cli.TIPOCLIENTE AS TIPOCLIENTE,
			tc.DESCRIPCION as TIPOCLIENTEDESC,
			cli.TIPODOCUMENTO AS TIPODOCUMENTO,
			td.DESCRIPCION AS TIPODOCUMENTODESC,
			cli.NUMERODOCUMENTO,
			cli.CODIGOSWIFT,
			cli.CODIGOESTADO		
		FROM 
			CLIENTE cli
				LEFT JOIN (SELECT 
								det.DESCRIPCION, 
								val.VALOR 
							FROM 
								PARAMETRO par 
									INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO 
									INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '007') pr ON cli.PAISRESIDENCIA = pr.VALOR --Tipo Pais

				LEFT JOIN (SELECT 
								det.DESCRIPCION, 
								val.VALOR 
							FROM 
								PARAMETRO par 
									INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO 
									INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '007') rp ON cli.RIESGOPAIS = rp.VALOR --Tipo Pais

				LEFT JOIN (SELECT 
								det.DESCRIPCION, 
								val.VALOR 
							FROM 
								PARAMETRO par 
									INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO 
									INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '009') cc ON cli.RECHAZARCARGA = cc.VALOR --Carga Cliente

				LEFT JOIN (SELECT 
								det.DESCRIPCION, 
								val.VALOR 
							FROM 
								PARAMETRO par 
									INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO 
									INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '004') tc ON cli.TIPOCLIENTE = tc.VALOR --Tipo Cliente   
				LEFT JOIN (SELECT 
								det.DESCRIPCION, 
								val.VALOR 
							FROM 
								PARAMETRO par 
									INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO 
									INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '040') td ON cli.TIPODOCUMENTO = td.VALOR --Tipo Documento
		WHERE 
			cli.CODIGOESTADO = 1 
			AND cli.CODIGO LIKE '%' || NVL(P_CODIGO,'') || '%' 
            AND UPPER(cli.NOMBRE) LIKE '%' ||  UPPER(NVL(P_NOMBRE,'')) || '%' 
			AND cli.TIPOCLIENTE = CASE WHEN P_TIPOCLIENTE = '-2' THEN cli.TIPOCLIENTE ELSE P_TIPOCLIENTE END
			AND (cli.CODIGO is null
			OR cli.NOMBRE is null
			OR cli.ENTIDAD is null
			OR cli.PAISRESIDENCIA is null
			OR cli.RIESGOPAIS is null
			OR cli.PLAZA is null
			OR cli.SECTOR is null
            OR cli.TIPODOCUMENTO is null);
	END IF;
END;

/

GRANT EXECUTE ON "PCBCRP"."SP_BCR_CLIENTE_LISTAR" TO "APP_PCBCRP";

-- FIN CPASCOS 

-- INICIO SEBASTIAN

--------------------------------------------------------
--  DELETE STORED PROCEDURES
--------------------------------------------------------
DROP PROCEDURE "PCBCRP"."SP_BCR_REPORTE4_OPERACIONES";
DROP PROCEDURE "PCBCRP"."SP_BCR_REPORTE4_ANEXO8_IRC";
DROP PROCEDURE "PCBCRP"."SP_BCR_REPORTE4_ANEXO8";
DROP PROCEDURE "PCBCRP"."SP_BCR_REPORTE8_ANEXO8";
DROP PROCEDURE "PCBCRP"."SP_BCR_REPORTE8_OPERACIONES";

--------------------------------------------------------
--  DDL for Procedure SP_BCR_REPORTE4_OPERACIONES
--------------------------------------------------------
create PROCEDURE  "PCBCRP"."SP_BCR_REPORTE4_OPERACIONES" (
P_IDPOSICIONCAMBIARIA	IN VARCHAR2,
P_FECHA                 IN DATE,
P_TIPOPROCESO           IN VARCHAR2,
CURSOR_ 	OUT SYS_REFCURSOR
)

AS

V_CODIGOBCR		    VARCHAR2(2);
V_TIPOOPERACION	    VARCHAR2(1);
V_TIPOCLIENTE	    VARCHAR2(1);
V_RESIDENTE		    VARCHAR2(1);
V_TIPOENTREGA	    VARCHAR2(1);
V_CALLPUT		    VARCHAR2(1);

V_CODIGOBCR_A		    VARCHAR2(2);
V_TIPOOPERACION_A	    VARCHAR2(1);
V_TIPOCLIENTE_A	    VARCHAR2(1);
V_RESIDENTE_A		    VARCHAR2(1);
V_TIPOENTREGA_A	    VARCHAR2(1);
V_CALLPUT_A		    VARCHAR2(1);

V_IDDIVISA          INTEGER;

BEGIN

   SELECT ID INTO V_IDDIVISA FROM DIVISA WHERE CODIGO = 'PEN';

    SELECT NVL(CODIGOBCR, ' '),  NVL(TIPO_OPERACION, ' ') , NVL(TIPO_CLIENTE, ' ') ,
    NVL(RESIDENTE, ' ') , NVL(TIPO_ENTREGA, ' ') , NVL(CALL_PUT, ' ')
    INTO V_CODIGOBCR, V_TIPOOPERACION, V_TIPOCLIENTE,
    V_RESIDENTE, V_TIPOENTREGA, V_CALLPUT
    FROM POSICION_CAMBIARIA WHERE ID = P_IDPOSICIONCAMBIARIA AND CODIGOESTADO = 1;
    
    SELECT CODIGOBCR,  TIPO_OPERACION , TIPO_CLIENTE,
    RESIDENTE , TIPO_ENTREGA , NVL(CALL_PUT, ' ')
    INTO V_CODIGOBCR_A, V_TIPOOPERACION_A, V_TIPOCLIENTE_A,
    V_RESIDENTE_A, V_TIPOENTREGA_A, V_CALLPUT_A
    FROM POSICION_CAMBIARIA WHERE ID = P_IDPOSICIONCAMBIARIA AND CODIGOESTADO = 1;

IF P_TIPOPROCESO ='D' THEN
    OPEN CURSOR_ FOR
    SELECT
			OPETEMP.PRODUCTO,
			OPETEMP.OPERACION AS NUMEROOPERACION,
			OPETEMP.CODIGOREPORTE,
			OPETEMP.CLIENTE,
			OPETEMP.NOMBRE,
			OPETEMP.TIPO,
			OPETEMP.DIVENTRADA,
			OPETEMP.DIVSALIDA,
			OPETEMP.IMPENTRADA,
			OPETEMP.IMPSALIDA,
			OPETEMP.TIPOCAMBIO,
			OPETEMP.VALIDACION,
			TO_CHAR(OPETEMP.CONTRATACION,'dd/mm/yyyy') AS CONTRATACION,
			TO_CHAR(OPETEMP.VALOR,'dd/mm/yyyy') AS VALOR,
			TO_CHAR(OPETEMP.VENCIMIENTO,'dd/mm/yyyy') AS VENCIMIENTO,
			OPETEMP.IMPORTEUSD,
			OPETEMP.TIPOCLIENTE
		FROM	(	SELECT

						p.CODIGO AS PRODUCTO,
						o.NUMEROOPERACION AS OPERACION,
						o.CODIGOREPORTE ,
						c.CODIGO AS CLIENTE,
						c.NOMBRE,
						mtto.DESCRIPCION AS TIPO,
						de.CODIGO AS DIVENTRADA,
						ds.CODIGO AS DIVSALIDA,
						o.IMPORTEDIVISAENTRADA AS IMPENTRADA,
						o.IMPORTEDIVISASALIDA AS IMPSALIDA,
						o.CAMBIOREF AS TIPOCAMBIO,
						o.VALIDACION,
						o.FECHACONTRATACION AS CONTRATACION,
						o.FECHAVALOR AS VALOR,
						o.FECHAVENCIMIENTO AS VENCIMIENTO,
						o.IMPORTEUSD,
						mttc.DESCRIPCION AS TIPOCLIENTE,
						o.ESTADO

					FROM
						OPERACION o
						INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
						INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
						INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
						INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '002'
									) mtto ON o.TIPOOPERACION = mtto.VALOR
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '004'
									) mttc ON o.TIPOCLIENTE = mttc.VALOR

						LEFT JOIN DIVISA dp ON dp.ID = o.IDDIVISAPRIMA
						LEFT JOIN DIVISA dex ON dex.ID = o.IDMONEDAEXTRANJERA
					WHERE
						o.ESTADO = 'L'
                        AND (o.IDDIVISAENTRADA = V_IDDIVISA OR o.IDDIVISASALIDA = V_IDDIVISA)
                        AND NVL(o.CODIGOREPORTE,' ') <> ' '
                        AND TRIM(o.TIPOPROCESO) = 'D'
                        AND o.CODIGOESTADO = 1

                        AND NVL(p.CODIGOBCR,' ') = V_CODIGOBCR
                        AND NVL(TRIM(o.TIPOOPERACION),' ') = V_TIPOOPERACION
                        AND NVL(c.TIPOCLIENTE,' ') = V_TIPOCLIENTE
                        AND NVL(o.RESIDENTE,' ') = CASE WHEN V_RESIDENTE = 'A' THEN NVL(o.RESIDENTE,' ') ELSE  V_RESIDENTE END
                        AND NVL(p.TIPOENTREGA,' ') = V_TIPOENTREGA
                        AND NVL(o.CALLPUT,' ') = V_CALLPUT
                        AND TO_DATE(TO_CHAR(o.FECHACONTRATACION, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND TO_DATE(TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))

                        AND o.NUMEROOPERACION NOT IN (
										SELECT NUMEROOPERACION
										FROM OPERACION
										WHERE
											ESTADO = 'A'
											AND TO_DATE(TO_CHAR(FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
											AND TRIM(TIPOPROCESO) = 'D'
									)

				) OPETEMP ORDER BY OPETEMP.CODIGOREPORTE, OPETEMP.OPERACION ASC;

ELSIF P_TIPOPROCESO ='A' THEN
    OPEN CURSOR_ FOR
        SELECT
			OPETEMP.PRODUCTO,
			OPETEMP.OPERACION AS NUMEROOPERACION,
			OPETEMP.CODIGOREPORTE,
			OPETEMP.CLIENTE,
			OPETEMP.NOMBRE,
			OPETEMP.TIPO,
			OPETEMP.DIVENTRADA,
			OPETEMP.DIVSALIDA,
			OPETEMP.IMPENTRADA,
			OPETEMP.IMPSALIDA,
			OPETEMP.TIPOCAMBIO,
			OPETEMP.VALIDACION,
			OPETEMP.CONTRATACION ,
			OPETEMP.VALOR,
			OPETEMP.VENCIMIENTO,
			OPETEMP.IMPORTEUSD,
			OPETEMP.TIPOCLIENTE
		FROM	(	SELECT

						p.CODIGO AS PRODUCTO,
						o.NUMEROOPERACION AS OPERACION,
						o.CODIGOREPORTE ,
						c.CODIGO AS CLIENTE,
						c.NOMBRE,
						mtto.DESCRIPCION AS TIPO,
						de.CODIGO AS DIVENTRADA,
						ds.CODIGO AS DIVSALIDA,
						o.IMPORTEDIVISAENTRADA AS IMPENTRADA,
						o.IMPORTEDIVISASALIDA AS IMPSALIDA,
						o.CAMBIOREF AS TIPOCAMBIO,
						TRIM(o.VALIDACION) AS VALIDACION,
						TO_CHAR(o.FECHACONTRATACION,'dd/mm/yyyy') AS CONTRATACION,
						TO_CHAR(o.FECHAVALOR,'dd/mm/yyyy') AS VALOR,
						TO_CHAR(o.FECHAVENCIMIENTO,'dd/mm/yyyy') AS VENCIMIENTO,
						o.IMPORTEUSD,
						mttc.DESCRIPCION AS TIPOCLIENTE,
						o.ESTADO

					FROM
						OPERACION o
						INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
						INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
						INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
						INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '002'
									) mtto ON o.TIPOOPERACION = mtto.VALOR
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '004'
									) mttc ON o.TIPOCLIENTE = mttc.VALOR

						LEFT JOIN DIVISA dp ON dp.ID = o.IDDIVISAPRIMA
						LEFT JOIN DIVISA dex ON dex.ID = o.IDMONEDAEXTRANJERA
					WHERE
						o.ESTADO = 'L'
                        AND (o.IDDIVISAENTRADA = V_IDDIVISA OR o.IDDIVISASALIDA = V_IDDIVISA)
                        AND NVL(o.CODIGOREPORTE,' ') <> ' '
                        AND TRIM(o.TIPOPROCESO) = 'D'
                        AND o.CODIGOESTADO = 1

                        AND NVL(p.CODIGOBCR,' ') = V_CODIGOBCR
                        AND NVL(TRIM(o.TIPOOPERACION),' ') = V_TIPOOPERACION
                        AND NVL(c.TIPOCLIENTE,' ') = V_TIPOCLIENTE
                        AND NVL(o.RESIDENTE,' ') = CASE WHEN V_RESIDENTE = 'A' THEN NVL(o.RESIDENTE,' ') ELSE  V_RESIDENTE END
                        AND NVL(p.TIPOENTREGA,' ') = V_TIPOENTREGA
                        AND NVL(o.CALLPUT,' ') = V_CALLPUT
                        AND TO_DATE(TO_CHAR(o.FECHACONTRATACION, 'dd/mm/yyyy')) < TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND TO_DATE(TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) < TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))

                        AND o.NUMEROOPERACION NOT IN (
										SELECT NUMEROOPERACION
										FROM OPERACION
										WHERE
											ESTADO = 'A'
											AND TO_DATE(TO_CHAR(FECHAMOVIMIENTO, 'dd/mm/yyyy')) < TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
											AND TRIM(TIPOPROCESO) = 'D'
									)
                UNION 

                SELECT

						p.CODIGO AS PRODUCTO,
						o.NUMEROOPERACION AS OPERACION,
						o.CODIGOREPORTE ,
						c.CODIGO AS CLIENTE,
						c.NOMBRE,
						mtto.DESCRIPCION AS TIPO,
						de.CODIGO AS DIVENTRADA,
						ds.CODIGO AS DIVSALIDA,
						o.IMPORTEDIVISAENTRADA AS IMPENTRADA,
						o.IMPORTEDIVISASALIDA AS IMPSALIDA,
						o.CAMBIOREF AS TIPOCAMBIO,
						TRIM(o.VALIDACION) AS VALIDACION,
						TO_CHAR(o.FECHACONTRATACION,'dd/mm/yyyy') AS CONTRATACION,
						TO_CHAR(o.FECHAVALOR,'dd/mm/yyyy') AS VALOR,
						TO_CHAR(o.FECHAVENCIMIENTO,'dd/mm/yyyy') AS VENCIMIENTO,
						o.IMPORTEUSD,
						mttc.DESCRIPCION AS TIPOCLIENTE,
						o.ESTADO

					FROM
						OPERACION o
						INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
						INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
						INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
						INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '002'
									) mtto ON o.TIPOOPERACION = mtto.VALOR
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '004'
									) mttc ON o.TIPOCLIENTE = mttc.VALOR

					WHERE
						o.ESTADO = 'L'
                        AND (o.IDDIVISAENTRADA = V_IDDIVISA OR o.IDDIVISASALIDA = V_IDDIVISA)
                        AND NVL(o.CODIGOREPORTE,' ') <> ' '
                        AND TRIM(o.TIPOPROCESO) = 'A'
                        AND o.CODIGOESTADO = 1

                        AND p.CODIGOBCR = V_CODIGOBCR_A
                        AND o.TIPOOPERACION = V_TIPOOPERACION_A
                        AND c.TIPOCLIENTE = V_TIPOCLIENTE_A
                        AND o.RESIDENTE = CASE WHEN V_RESIDENTE_A = 'A' THEN o.RESIDENTE ELSE  V_RESIDENTE_A END
                        AND p.TIPOENTREGA = V_TIPOENTREGA_A
                        AND NVL(o.CALLPUT,' ') = V_CALLPUT

                        AND TO_CHAR(o.FECHACONTRATACION, 'dd/mm/yyyy') = TO_CHAR(P_FECHA, 'dd/mm/yyyy')
                        AND TO_DATE(TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy') = TO_CHAR(P_FECHA,'dd/mm/yyyy')
                        AND o.NUMEROOPERACION NOT IN (
										SELECT NUMEROOPERACION
										FROM OPERACION
										WHERE
											ESTADO = 'A'
											AND TO_DATE(TO_CHAR(FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
											AND TRIM(TIPOPROCESO) = 'A'
									)

				) OPETEMP ORDER BY OPETEMP.CODIGOREPORTE, OPETEMP.OPERACION ASC;
    END IF;
END;
/
--------------------------------------------------------
--  DDL for Procedure SP_BCR_REPORTE4_ANEXO8_IRC
--------------------------------------------------------
create PROCEDURE  "PCBCRP"."SP_BCR_REPORTE4_ANEXO8_IRC" (
P_IDPOSICIONCAMBIARIA	IN VARCHAR2,
P_FECHA                 IN DATE,
P_TIPOPROCESO           IN VARCHAR2,
CURSOR_ 	OUT SYS_REFCURSOR
)

AS

V_CODIGOBCR		    VARCHAR2(2);
V_TIPOOPERACION	    VARCHAR2(1);
V_TIPOCLIENTE	    VARCHAR2(1);
V_RESIDENTE		    VARCHAR2(1);
V_TIPOENTREGA	    VARCHAR2(1);
V_CALLPUT		    VARCHAR2(1);
V_IDDIVISA          INTEGER;

BEGIN

   SELECT ID INTO V_IDDIVISA FROM DIVISA WHERE CODIGO = 'PEN';

    SELECT NVL(CODIGOBCR, ' '),  NVL(TIPO_OPERACION, ' ') , NVL(TIPO_CLIENTE, ' ') ,
    NVL(RESIDENTE, ' ') , NVL(TIPO_ENTREGA, ' ') , NVL(CALL_PUT, ' ')
    INTO V_CODIGOBCR, V_TIPOOPERACION, V_TIPOCLIENTE,
    V_RESIDENTE, V_TIPOENTREGA, V_CALLPUT
    FROM POSICION_CAMBIARIA WHERE ID = P_IDPOSICIONCAMBIARIA;

IF P_TIPOPROCESO ='D' THEN
    OPEN CURSOR_ FOR
    SELECT
			OPETEMP.PRODUCTO,
            OPETEMP.OPERACION AS NUMEROOPERACION ,
			OPETEMP.CODIGOREPORTE,
			OPETEMP.CLIENTE,
			OPETEMP.NOMBRE,
            OPETEMP.TIPO,
            OPETEMP.DIVENTRADA,
            OPETEMP.DIVSALIDA,
            SUM(OPETEMP.IMPENTRADA) AS IMPENTRADA,
            SUM(OPETEMP.IMPSALIDA) AS IMPSALIDA,
            OPETEMP.TIPOCAMBIO,
            OPETEMP.VALIDACION,
            MAX(TO_CHAR(OPETEMP.CONTRATACION,'dd/mm/yyyy')) AS CONTRATACION,
            MIN(TO_CHAR(OPETEMP.VALOR,'dd/mm/yyyy')) AS VALOR,
            MAX(TO_CHAR(OPETEMP.VENCIMIENTO,'dd/mm/yyyy')) AS VENCIMIENTO,
			SUM(OPETEMP.IMPORTEUSD) AS IMPORTEUSD,
            OPETEMP.TIPOCLIENTE
		FROM	(	SELECT

						p.CODIGO AS PRODUCTO,
						SUBSTR(o.NUMEROOPERACION,0, LENGTH(o.NUMEROOPERACION)-3) AS OPERACION,
						o.CODIGOREPORTE ,
						c.CODIGO AS CLIENTE,
						c.NOMBRE,
						mtto.DESCRIPCION AS TIPO,
						de.CODIGO AS DIVENTRADA,
						ds.CODIGO AS DIVSALIDA,
						o.IMPORTEDIVISAENTRADA AS IMPENTRADA,
						o.IMPORTEDIVISASALIDA AS IMPSALIDA,
						o.CAMBIOREF AS TIPOCAMBIO,
						'' AS VALIDACION,
						o.FECHACONTRATACION AS CONTRATACION,
						o.FECHAVALOR AS VALOR,
						o.FECHAVENCIMIENTO AS VENCIMIENTO,
						o.IMPORTEUSD,
						mttc.DESCRIPCION AS TIPOCLIENTE,
						o.ESTADO

					FROM
						OPERACION o
						INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
						INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
						INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
						INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '002'
									) mtto ON o.TIPOOPERACION = mtto.VALOR
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '004'
									) mttc ON o.TIPOCLIENTE = mttc.VALOR

						LEFT JOIN DIVISA dp ON dp.ID = o.IDDIVISAPRIMA
						LEFT JOIN DIVISA dex ON dex.ID = o.IDMONEDAEXTRANJERA
					WHERE
						o.ESTADO = 'L'
                        AND (o.IDDIVISAENTRADA = V_IDDIVISA OR o.IDDIVISASALIDA = V_IDDIVISA)
                        AND NVL(o.CODIGOREPORTE,' ') <> ' '
                        AND TRIM(o.TIPOPROCESO) = 'D'
                        AND o.CODIGOESTADO = 1

                        AND NVL(p.CODIGOBCR,' ') = V_CODIGOBCR
                        AND NVL(TRIM(o.TIPOOPERACION),' ') = V_TIPOOPERACION
                        AND NVL(c.TIPOCLIENTE,' ') = V_TIPOCLIENTE
                        AND NVL(o.RESIDENTE,' ') = CASE WHEN V_RESIDENTE = 'A' THEN NVL(o.RESIDENTE,' ') ELSE  V_RESIDENTE END
                        AND NVL(p.TIPOENTREGA,' ') = V_TIPOENTREGA
                        AND NVL(o.CALLPUT,' ') = V_CALLPUT
                        AND TO_DATE(TO_CHAR(o.FECHACONTRATACION, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND TO_DATE(TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND p.id IN  (SELECT ID FROM PRODUCTO WHERE CODIGO='IRC')
                        AND o.NUMEROOPERACION NOT IN (
										SELECT NUMEROOPERACION
										FROM OPERACION
										WHERE
											ESTADO = 'A'
											AND TO_DATE(TO_CHAR(FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
											AND TRIM(TIPOPROCESO) = 'D'
									)
				) OPETEMP
                GROUP BY OPETEMP.PRODUCTO, OPETEMP.OPERACION, OPETEMP.CODIGOREPORTE, OPETEMP.CLIENTE, OPETEMP.NOMBRE,
                OPETEMP.TIPO, OPETEMP.DIVENTRADA, OPETEMP.DIVSALIDA, OPETEMP.TIPOCLIENTE, OPETEMP.TIPOCAMBIO, OPETEMP.VALIDACION
                ORDER BY OPETEMP.CODIGOREPORTE ASC , OPETEMP.OPERACION ASC;

ELSIF P_TIPOPROCESO ='A' THEN
    OPEN CURSOR_ FOR
        SELECT
			OPETEMP.PRODUCTO,
            OPETEMP.OPERACION AS NUMEROOPERACION ,
			OPETEMP.CODIGOREPORTE,
			OPETEMP.CLIENTE,
			OPETEMP.NOMBRE,
            OPETEMP.TIPO,
            OPETEMP.DIVENTRADA,
            OPETEMP.DIVSALIDA,
            SUM(OPETEMP.IMPENTRADA) AS IMPENTRADA,
            SUM(OPETEMP.IMPSALIDA) AS IMPSALIDA,
            OPETEMP.TIPOCAMBIO,
            OPETEMP.VALIDACION,
            MAX(TO_CHAR(OPETEMP.CONTRATACION,'dd/mm/yyyy')) AS CONTRATACION,
            MIN(TO_CHAR(OPETEMP.VALOR,'dd/mm/yyyy')) AS VALOR,
            MAX(TO_CHAR(OPETEMP.VENCIMIENTO,'dd/mm/yyyy')) AS VENCIMIENTO,
			SUM(OPETEMP.IMPORTEUSD) AS IMPORTEUSD,
            OPETEMP.TIPOCLIENTE
		FROM	(	SELECT

						p.CODIGO AS PRODUCTO,
						SUBSTR(o.NUMEROOPERACION,0, LENGTH(o.NUMEROOPERACION)-3) AS OPERACION,
						o.CODIGOREPORTE ,
						c.CODIGO AS CLIENTE,
						c.NOMBRE,
						mtto.DESCRIPCION AS TIPO,
						de.CODIGO AS DIVENTRADA,
						ds.CODIGO AS DIVSALIDA,
						o.IMPORTEDIVISAENTRADA AS IMPENTRADA,
						o.IMPORTEDIVISASALIDA AS IMPSALIDA,
						o.CAMBIOREF AS TIPOCAMBIO,
						'' AS VALIDACION,
						o.FECHACONTRATACION AS CONTRATACION,
						o.FECHAVALOR AS VALOR,
						o.FECHAVENCIMIENTO AS VENCIMIENTO,
						o.IMPORTEUSD,
						mttc.DESCRIPCION AS TIPOCLIENTE,
						o.ESTADO

					FROM
						OPERACION o
						INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
						INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
						INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
						INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '002'
									) mtto ON o.TIPOOPERACION = mtto.VALOR
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '004'
									) mttc ON o.TIPOCLIENTE = mttc.VALOR

						LEFT JOIN DIVISA dp ON dp.ID = o.IDDIVISAPRIMA
						LEFT JOIN DIVISA dex ON dex.ID = o.IDMONEDAEXTRANJERA
					WHERE
						o.ESTADO = 'L'
                        AND (o.IDDIVISAENTRADA = V_IDDIVISA OR o.IDDIVISASALIDA = V_IDDIVISA)
                        AND NVL(o.CODIGOREPORTE,' ') <> ' '
                        AND TRIM(o.TIPOPROCESO) = 'D'
                        AND o.CODIGOESTADO = 1

                        AND NVL(p.CODIGOBCR,' ') = V_CODIGOBCR
                        AND NVL(TRIM(o.TIPOOPERACION),' ') = V_TIPOOPERACION
                        AND NVL(c.TIPOCLIENTE,' ') = V_TIPOCLIENTE
                        AND NVL(o.RESIDENTE,' ') = CASE WHEN V_RESIDENTE = 'A' THEN NVL(o.RESIDENTE,' ') ELSE  V_RESIDENTE END
                        AND NVL(p.TIPOENTREGA,' ') = V_TIPOENTREGA
                        AND NVL(o.CALLPUT,' ') = V_CALLPUT
                        AND TO_DATE(TO_CHAR(o.FECHACONTRATACION, 'dd/mm/yyyy')) < TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND TO_DATE(TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) < TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND p.id IN  (SELECT ID FROM PRODUCTO WHERE CODIGO='IRC')
                        AND o.NUMEROOPERACION NOT IN (
										SELECT NUMEROOPERACION
										FROM OPERACION
										WHERE
											ESTADO = 'A'
											AND TO_DATE(TO_CHAR(FECHAMOVIMIENTO, 'dd/mm/yyyy')) < TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
											AND TRIM(TIPOPROCESO) = 'D'
									)
                UNION 

                SELECT

						p.CODIGO AS PRODUCTO,
						SUBSTR(o.NUMEROOPERACION,0, LENGTH(o.NUMEROOPERACION)-3) AS OPERACION,
						o.CODIGOREPORTE ,
						c.CODIGO AS CLIENTE,
						c.NOMBRE,
						mtto.DESCRIPCION AS TIPO,
						de.CODIGO AS DIVENTRADA,
						ds.CODIGO AS DIVSALIDA,
						o.IMPORTEDIVISAENTRADA AS IMPENTRADA,
						o.IMPORTEDIVISASALIDA AS IMPSALIDA,
						o.CAMBIOREF AS TIPOCAMBIO,
						'' AS VALIDACION,
						o.FECHACONTRATACION AS CONTRATACION,
						o.FECHAVALOR AS VALOR,
						o.FECHAVENCIMIENTO AS VENCIMIENTO,
						o.IMPORTEUSD,
						mttc.DESCRIPCION AS TIPOCLIENTE,
						o.ESTADO

					FROM
						OPERACION o
						INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
						INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
						INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
						INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '002'
									) mtto ON o.TIPOOPERACION = mtto.VALOR
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '004'
									) mttc ON o.TIPOCLIENTE = mttc.VALOR

					WHERE
						o.ESTADO = 'L'
                        AND (o.IDDIVISAENTRADA = V_IDDIVISA OR o.IDDIVISASALIDA = V_IDDIVISA)
                        AND NVL(o.CODIGOREPORTE,' ') <> ' '
                        AND TRIM(o.TIPOPROCESO) = P_TIPOPROCESO
                        AND o.CODIGOESTADO = 1

                        AND NVL(p.CODIGOBCR,' ') = V_CODIGOBCR
                        AND NVL(TRIM(o.TIPOOPERACION),' ') = V_TIPOOPERACION
                        AND NVL(c.TIPOCLIENTE,' ') = V_TIPOCLIENTE
                        AND NVL(o.RESIDENTE,' ') = CASE WHEN V_RESIDENTE = 'A' THEN NVL(o.RESIDENTE,' ') ELSE  V_RESIDENTE END
                        AND NVL(p.TIPOENTREGA,' ') = V_TIPOENTREGA
                        AND NVL(o.CALLPUT,' ') = V_CALLPUT

                        AND TO_CHAR(o.FECHACONTRATACION, 'dd/mm/yyyy') = TO_CHAR(P_FECHA, 'dd/mm/yyyy')
                        AND TO_DATE(TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy') = TO_CHAR(P_FECHA,'dd/mm/yyyy')
                        AND p.id IN  (SELECT ID FROM PRODUCTO WHERE CODIGO='IRC')
                        AND o.NUMEROOPERACION NOT IN (
										SELECT NUMEROOPERACION
										FROM OPERACION
										WHERE
											ESTADO = 'A'
											AND TO_DATE(TO_CHAR(FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
											AND TRIM(TIPOPROCESO) = P_TIPOPROCESO
									)

				) OPETEMP
                GROUP BY OPETEMP.PRODUCTO, OPETEMP.OPERACION, OPETEMP.CODIGOREPORTE, OPETEMP.CLIENTE, OPETEMP.NOMBRE,
                OPETEMP.TIPO, OPETEMP.DIVENTRADA, OPETEMP.DIVSALIDA, OPETEMP.TIPOCLIENTE, OPETEMP.TIPOCAMBIO, OPETEMP.VALIDACION
                ORDER BY OPETEMP.CODIGOREPORTE ASC , OPETEMP.OPERACION ASC;
    END IF;
END;
/
--------------------------------------------------------
--  DDL for Procedure SP_BCR_REPORTE4_ANEXO8
--------------------------------------------------------
create PROCEDURE  "PCBCRP"."SP_BCR_REPORTE4_ANEXO8" (
P_IDPOSICIONCAMBIARIA	IN VARCHAR2,
P_FECHA                 IN DATE,
P_TIPOPROCESO           IN VARCHAR2,
CURSOR_ 	OUT SYS_REFCURSOR
)

AS

V_CODIGOBCR		    VARCHAR2(2);
V_TIPOOPERACION	    VARCHAR2(1);
V_TIPOCLIENTE	    VARCHAR2(1);
V_RESIDENTE		    VARCHAR2(1);
V_TIPOENTREGA	    VARCHAR2(1);
V_CALLPUT		    VARCHAR2(1);
V_IDDIVISA          INTEGER;

BEGIN

   SELECT ID INTO V_IDDIVISA FROM DIVISA WHERE CODIGO = 'PEN';

    SELECT NVL(CODIGOBCR, ' '),  NVL(TIPO_OPERACION, ' ') , NVL(TIPO_CLIENTE, ' ') ,
    NVL(RESIDENTE, ' ') , NVL(TIPO_ENTREGA, ' ') , NVL(CALL_PUT, ' ')
    INTO V_CODIGOBCR, V_TIPOOPERACION, V_TIPOCLIENTE,
    V_RESIDENTE, V_TIPOENTREGA, V_CALLPUT
    FROM POSICION_CAMBIARIA WHERE ID = P_IDPOSICIONCAMBIARIA;

IF P_TIPOPROCESO ='D' THEN
    OPEN CURSOR_ FOR
    SELECT
			OPETEMP.PRODUCTO,
			OPETEMP.OPERACION AS NUMEROOPERACION,
			OPETEMP.CODIGOREPORTE,
			OPETEMP.CLIENTE,
			OPETEMP.NOMBRE,
			OPETEMP.TIPO,
			OPETEMP.DIVENTRADA,
			OPETEMP.DIVSALIDA,
			OPETEMP.IMPENTRADA,
			OPETEMP.IMPSALIDA,
			OPETEMP.TIPOCAMBIO,
			OPETEMP.VALIDACION,
			TO_CHAR(OPETEMP.CONTRATACION,'dd/mm/yyyy') AS CONTRATACION,
			TO_CHAR(OPETEMP.VALOR,'dd/mm/yyyy') AS VALOR,
			TO_CHAR(OPETEMP.VENCIMIENTO,'dd/mm/yyyy') AS VENCIMIENTO,
			OPETEMP.IMPORTEUSD,
			OPETEMP.TIPOCLIENTE
		FROM	(	SELECT

						p.CODIGO AS PRODUCTO,
						o.NUMEROOPERACION AS OPERACION,
						o.CODIGOREPORTE ,
						c.CODIGO AS CLIENTE,
						c.NOMBRE,
						mtto.DESCRIPCION AS TIPO,
						de.CODIGO AS DIVENTRADA,
						ds.CODIGO AS DIVSALIDA,
						o.IMPORTEDIVISAENTRADA AS IMPENTRADA,
						o.IMPORTEDIVISASALIDA AS IMPSALIDA,
						o.CAMBIOREF AS TIPOCAMBIO,
						o.VALIDACION,
						o.FECHACONTRATACION AS CONTRATACION,
						o.FECHAVALOR AS VALOR,
						o.FECHAVENCIMIENTO AS VENCIMIENTO,
						o.IMPORTEUSD,
						mttc.DESCRIPCION AS TIPOCLIENTE,
						o.ESTADO

					FROM
						OPERACION o
						INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
						INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
						INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
						INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '002'
									) mtto ON o.TIPOOPERACION = mtto.VALOR
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '004'
									) mttc ON o.TIPOCLIENTE = mttc.VALOR

						LEFT JOIN DIVISA dp ON dp.ID = o.IDDIVISAPRIMA
						LEFT JOIN DIVISA dex ON dex.ID = o.IDMONEDAEXTRANJERA
					WHERE
						o.ESTADO = 'L'
                        AND (o.IDDIVISAENTRADA = V_IDDIVISA OR o.IDDIVISASALIDA = V_IDDIVISA)
                        AND NVL(o.CODIGOREPORTE,' ') <> ' '
                        AND TRIM(o.TIPOPROCESO) = 'D'
                        AND o.CODIGOESTADO = 1

                        AND NVL(p.CODIGOBCR,' ') = V_CODIGOBCR
                        AND NVL(TRIM(o.TIPOOPERACION),' ') = V_TIPOOPERACION
                        AND NVL(c.TIPOCLIENTE,' ') = V_TIPOCLIENTE
                        AND NVL(o.RESIDENTE,' ') = CASE WHEN V_RESIDENTE = 'A' THEN NVL(o.RESIDENTE,' ') ELSE  V_RESIDENTE END
                        AND NVL(p.TIPOENTREGA,' ') = V_TIPOENTREGA
                        AND NVL(o.CALLPUT,' ') = V_CALLPUT
                        AND TO_DATE(TO_CHAR(o.FECHACONTRATACION, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND TO_DATE(TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND p.id NOT IN  (SELECT ID FROM PRODUCTO WHERE CODIGO='IRC')
                        AND o.NUMEROOPERACION NOT IN (
										SELECT NUMEROOPERACION
										FROM OPERACION
										WHERE
											ESTADO = 'A'
											AND TO_DATE(TO_CHAR(FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
											AND TRIM(TIPOPROCESO) = 'D'
									)
				) OPETEMP ORDER BY OPETEMP.CODIGOREPORTE ASC , OPETEMP.OPERACION ASC;

ELSIF P_TIPOPROCESO ='A' THEN
    OPEN CURSOR_ FOR
        SELECT
			OPETEMP.PRODUCTO,
			OPETEMP.OPERACION AS NUMEROOPERACION,
			OPETEMP.CODIGOREPORTE,
			OPETEMP.CLIENTE,
			OPETEMP.NOMBRE,
			OPETEMP.TIPO,
			OPETEMP.DIVENTRADA,
			OPETEMP.DIVSALIDA,
			OPETEMP.IMPENTRADA,
			OPETEMP.IMPSALIDA,
			OPETEMP.TIPOCAMBIO,
			OPETEMP.VALIDACION,
			TO_CHAR(OPETEMP.CONTRATACION,'dd/mm/yyyy') AS CONTRATACION,
			TO_CHAR(OPETEMP.VALOR,'dd/mm/yyyy') AS VALOR,
			TO_CHAR(OPETEMP.VENCIMIENTO,'dd/mm/yyyy') AS VENCIMIENTO,
			OPETEMP.IMPORTEUSD,
			OPETEMP.TIPOCLIENTE
		FROM	(	SELECT

						p.CODIGO AS PRODUCTO,
						o.NUMEROOPERACION AS OPERACION,
						o.CODIGOREPORTE ,
						c.CODIGO AS CLIENTE,
						c.NOMBRE,
						mtto.DESCRIPCION AS TIPO,
						de.CODIGO AS DIVENTRADA,
						ds.CODIGO AS DIVSALIDA,
						o.IMPORTEDIVISAENTRADA AS IMPENTRADA,
						o.IMPORTEDIVISASALIDA AS IMPSALIDA,
						o.CAMBIOREF AS TIPOCAMBIO,
						o.VALIDACION,
						o.FECHACONTRATACION AS CONTRATACION,
						o.FECHAVALOR AS VALOR,
						o.FECHAVENCIMIENTO AS VENCIMIENTO,
						o.IMPORTEUSD,
						mttc.DESCRIPCION AS TIPOCLIENTE,
						o.ESTADO

					FROM
						OPERACION o
						INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
						INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
						INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
						INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '002'
									) mtto ON o.TIPOOPERACION = mtto.VALOR
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '004'
									) mttc ON o.TIPOCLIENTE = mttc.VALOR

						LEFT JOIN DIVISA dp ON dp.ID = o.IDDIVISAPRIMA
						LEFT JOIN DIVISA dex ON dex.ID = o.IDMONEDAEXTRANJERA
					WHERE
						o.ESTADO = 'L'
                        AND (o.IDDIVISAENTRADA = V_IDDIVISA OR o.IDDIVISASALIDA = V_IDDIVISA)
                        AND NVL(o.CODIGOREPORTE,' ') <> ' '
                        AND TRIM(o.TIPOPROCESO) = 'D'
                        AND o.CODIGOESTADO = 1

                        AND NVL(p.CODIGOBCR,' ') = V_CODIGOBCR
                        AND NVL(TRIM(o.TIPOOPERACION),' ') = V_TIPOOPERACION
                        AND NVL(c.TIPOCLIENTE,' ') = V_TIPOCLIENTE
                        AND NVL(o.RESIDENTE,' ') = CASE WHEN V_RESIDENTE = 'A' THEN NVL(o.RESIDENTE,' ') ELSE  V_RESIDENTE END
                        AND NVL(p.TIPOENTREGA,' ') = V_TIPOENTREGA
                        AND NVL(o.CALLPUT,' ') = V_CALLPUT
                        AND TO_DATE(TO_CHAR(o.FECHACONTRATACION, 'dd/mm/yyyy')) < TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND TO_DATE(TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) < TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND p.id NOT IN  (SELECT ID FROM PRODUCTO WHERE CODIGO='IRC')
                        AND o.NUMEROOPERACION NOT IN (
										SELECT NUMEROOPERACION
										FROM OPERACION
										WHERE
											ESTADO = 'A'
											AND TO_DATE(TO_CHAR(FECHAMOVIMIENTO, 'dd/mm/yyyy')) < TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
											AND TRIM(TIPOPROCESO) = 'D'
									)
                UNION ALL

                SELECT

						p.CODIGO AS PRODUCTO,
						o.NUMEROOPERACION AS OPERACION,
						o.CODIGOREPORTE ,
						c.CODIGO AS CLIENTE,
						c.NOMBRE,
						mtto.DESCRIPCION AS TIPO,
						de.CODIGO AS DIVENTRADA,
						ds.CODIGO AS DIVSALIDA,
						o.IMPORTEDIVISAENTRADA AS IMPENTRADA,
						o.IMPORTEDIVISASALIDA AS IMPSALIDA,
						o.CAMBIOREF AS TIPOCAMBIO,
						o.VALIDACION,
						o.FECHACONTRATACION AS CONTRATACION,
						o.FECHAVALOR AS VALOR,
						o.FECHAVENCIMIENTO AS VENCIMIENTO,
						o.IMPORTEUSD,
						mttc.DESCRIPCION AS TIPOCLIENTE,
						o.ESTADO

					FROM
						OPERACION o
						INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
						INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
						INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
						INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '002'
									) mtto ON o.TIPOOPERACION = mtto.VALOR
						INNER JOIN (SELECT
										det.DESCRIPCION,
										val.VALOR
									FROM
										PARAMETRO par
										INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
										INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '004'
									) mttc ON o.TIPOCLIENTE = mttc.VALOR

					WHERE
						o.ESTADO = 'L'
                        AND (o.IDDIVISAENTRADA = V_IDDIVISA OR o.IDDIVISASALIDA = V_IDDIVISA)
                        AND NVL(o.CODIGOREPORTE,' ') <> ' '
                        AND TRIM(o.TIPOPROCESO) = P_TIPOPROCESO
                        AND o.CODIGOESTADO = 1

                        AND NVL(p.CODIGOBCR,' ') = V_CODIGOBCR
                        AND NVL(TRIM(o.TIPOOPERACION),' ') = V_TIPOOPERACION
                        AND NVL(c.TIPOCLIENTE,' ') = V_TIPOCLIENTE
                        AND NVL(o.RESIDENTE,' ') = CASE WHEN V_RESIDENTE = 'A' THEN NVL(o.RESIDENTE,' ') ELSE  V_RESIDENTE END
                        AND NVL(p.TIPOENTREGA,' ') = V_TIPOENTREGA
                        AND NVL(o.CALLPUT,' ') = V_CALLPUT

                        AND TO_CHAR(o.FECHACONTRATACION, 'dd/mm/yyyy') = TO_CHAR(P_FECHA, 'dd/mm/yyyy')
                        AND TO_DATE(TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
                        AND TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy') = TO_CHAR(P_FECHA,'dd/mm/yyyy')
                        AND p.id NOT IN  (SELECT ID FROM PRODUCTO WHERE CODIGO='IRC')
                        AND o.NUMEROOPERACION NOT IN (
										SELECT NUMEROOPERACION
										FROM OPERACION
										WHERE
											ESTADO = 'A'
											AND TO_DATE(TO_CHAR(FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA,'dd/mm/yyyy'))
											AND TRIM(TIPOPROCESO) = P_TIPOPROCESO
									)

				) OPETEMP ORDER BY OPETEMP.CODIGOREPORTE ASC;
    END IF;
END;
/
--------------------------------------------------------
--  DDL for Procedure SP_BCR_REPORTE8_ANEXO8
--------------------------------------------------------
create PROCEDURE  "PCBCRP"."SP_BCR_REPORTE8_ANEXO8" (
P_IDSALDODERIVADOS  	IN VARCHAR2,
P_FECHA                 IN DATE,
P_TIPOPROCESO           IN VARCHAR2,
CURSOR_ 	OUT SYS_REFCURSOR
)

AS

V_CODIGOOPERACION       VARCHAR2(4);

BEGIN
    SELECT CODIGOOPERACION INTO V_CODIGOOPERACION FROM SALDO_DERIVADOS WHERE ID = P_IDSALDODERIVADOS;

    IF V_CODIGOOPERACION = '0603' THEN
        OPEN CURSOR_ FOR

         SELECT
			OPETEMP.PRODUCTO,
            OPETEMP.NUMEROOPERACION,
			OPETEMP.CODIGOREPORTE,
			OPETEMP.CLIENTE,
			OPETEMP.NOMBRE,
            OPETEMP.TIPODOCUMENTO,
            OPETEMP.TIPOCLIENTE,
            OPETEMP.VALIDACION,
            MAX(TO_CHAR(OPETEMP.CONTRATACION,'dd/mm/yyyy')) AS CONTRATACION,
            MAX(TO_CHAR(OPETEMP.VENCIMIENTO,'dd/mm/yyyy')) AS VENCIMIENTO,
			SUM(OPETEMP.IMPORTEUSD) AS IMPORTEUSD,
            OPETEMP.ESTADO

		FROM	(
            SELECT
                p.CODIGO AS PRODUCTO,
                SUBSTR(o.NUMEROOPERACION,0, LENGTH(o.NUMEROOPERACION)-3) AS NUMEROOPERACION,
                o.CODIGOREPORTE ,
                c.CODIGO AS CLIENTE,
                c.NOMBRE,
                c.TIPODOCUMENTO,
                o.TIPOCLIENTE,
                '' AS VALIDACION,
                o.FECHACONTRATACION AS CONTRATACION,
                o.FECHAVENCIMIENTO AS VENCIMIENTO,
                o.IMPORTEUSD,
                '' AS ESTADO
            FROM TASA_INTERES o
                INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
                INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
                INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
                INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
                LEFT JOIN DIVISA dp ON dp.ID = o.IDDIVISAPRIMA
                LEFT JOIN DIVISA dex ON dex.ID = o.IDMONEDAEXTRANJERA
            WHERE
                o.ESTADO <> 'A' --Anulada
                AND o.CODIGOESTADO = 1
                AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA, 'dd/mm/yyyy'))
                --QUITO LAS VENCIDAS
                AND TO_DATE(TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHA, 'dd/mm/yyyy'))
                AND o.TIPOPROCESO = 'D'
                AND o.ID_PRODUCTO = (SELECT p.ID FROM PRODUCTO p WHERE p.CODIGO = 'IRD') --@i_idProductoIRD
            )OPETEMP
               GROUP BY OPETEMP.PRODUCTO, OPETEMP.NUMEROOPERACION, OPETEMP.CODIGOREPORTE, OPETEMP.CLIENTE, OPETEMP.NOMBRE,
                 OPETEMP.TIPODOCUMENTO,OPETEMP.TIPOCLIENTE,OPETEMP.VALIDACION, OPETEMP.ESTADO
                ORDER BY OPETEMP.NUMEROOPERACION, OPETEMP.CODIGOREPORTE ASC;

    ELSIF V_CODIGOOPERACION = '0706' THEN
        OPEN CURSOR_ FOR
            SELECT
                p.CODIGO AS PRODUCTO,
                o.NUMEROOPERACION AS NUMEROOPERACION,
                o.CODIGOREPORTE ,
                c.CODIGO AS CLIENTE,
                c.NOMBRE,
                c.TIPODOCUMENTO,
                o.TIPOCLIENTE,
                '' AS  VALIDACION,
                o.FECHAREPORTE AS CONTRATACION,
                o.FECHATERMINO AS VENCIMIENTO,
                o.IMPORTEUSD,
                '' AS ESTADO

            FROM OPERACION_DERIVADO o
                INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
                INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
                INNER JOIN DIVISA d ON d.ID = o.IDDIVISA
            WHERE
                o.CODIGOESTADO = 1
                AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA, 'dd/mm/yyyy'))
                --QUITO LAS VENCIDAS
                AND TO_DATE(TO_CHAR(o.FECHATERMINO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHA, 'dd/mm/yyyy'))
                AND o.TIPOPROCESO = 'D'
                AND o.ID_PRODUCTO IN (SELECT p.ID FROM PRODUCTO p WHERE p.CODIGO IN ('ODIV'))
                AND c.CODIGO NOT IN ('PER013597')
                ORDER BY o.NUMEROOPERACION, o.CODIGOREPORTE;

    ELSIF V_CODIGOOPERACION = '0799' THEN
        OPEN CURSOR_ FOR
            SELECT
                p.CODIGO AS PRODUCTO,
                o.NUMEROOPERACION AS NUMEROOPERACION,
                o.CODIGOREPORTE ,
                c.CODIGO AS CLIENTE,
                c.NOMBRE,
                c.TIPODOCUMENTO,
                o.TIPOCLIENTE,
                '' AS VALIDACION,
                o.FECHAREPORTE AS CONTRATACION,
                o.FECHATERMINO AS VENCIMIENTO,
                o.IMPORTEUSD,
                '' AS ESTADO
            FROM OPERACION_DERIVADO o
                INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
                INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
                INNER JOIN DIVISA d ON d.ID = o.IDDIVISA
            WHERE
                o.CODIGOESTADO = 1
                AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA, 'dd/mm/yyyy'))
                --QUITO LAS VENCIDAS
                AND TO_DATE(TO_CHAR(o.FECHATERMINO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHA, 'dd/mm/yyyy'))
                AND o.TIPOPROCESO = 'D'
                AND o.ID_PRODUCTO IN (SELECT p.ID FROM PRODUCTO p WHERE p.CODIGO IN ('OTO'))
                ORDER BY o.NUMEROOPERACION, o.CODIGOREPORTE;

    END IF;
END;
/
--------------------------------------------------------
--  DDL for Procedure SP_BCR_REPORTE8_OPERACIONES
--------------------------------------------------------
create PROCEDURE  "PCBCRP"."SP_BCR_REPORTE8_OPERACIONES" (
P_IDSALDODERIVADOS  	IN VARCHAR2,
P_FECHA                 IN DATE,
P_TIPOPROCESO           IN VARCHAR2,
CURSOR_ 	OUT SYS_REFCURSOR
)

AS

V_CODIGOOPERACION       VARCHAR2(4);

BEGIN
    SELECT CODIGOOPERACION INTO V_CODIGOOPERACION FROM SALDO_DERIVADOS WHERE ID = P_IDSALDODERIVADOS;

    IF V_CODIGOOPERACION = '0603' THEN
        OPEN CURSOR_ FOR
            SELECT
                p.CODIGO AS PRODUCTO,
                o.NUMEROOPERACION AS NUMEROOPERACION,
                o.CODIGOREPORTE ,
                c.CODIGO AS CLIENTE,
                c.NOMBRE,
                c.TIPODOCUMENTO,
                o.TIPOCLIENTE,
                o.VALIDACION,
                o.FECHACONTRATACION AS CONTRATACION,
                o.FECHAVENCIMIENTO AS VENCIMIENTO,
                o.IMPORTEUSD,
                o.ESTADO
            FROM TASA_INTERES o
                INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
                INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
                INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
                INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
                LEFT JOIN DIVISA dp ON dp.ID = o.IDDIVISAPRIMA
                LEFT JOIN DIVISA dex ON dex.ID = o.IDMONEDAEXTRANJERA
            WHERE
                o.ESTADO <> 'A' --Anulada
                AND o.CODIGOESTADO = 1
                AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA, 'dd/mm/yyyy'))
                --QUITO LAS VENCIDAS
                AND TO_DATE(TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHA, 'dd/mm/yyyy'))
                AND o.TIPOPROCESO = 'D'
                AND o.ID_PRODUCTO = (SELECT p.ID FROM PRODUCTO p WHERE p.CODIGO = 'IRD') --@i_idProductoIRD
                ORDER BY o.NUMEROOPERACION, o.CODIGOREPORTE ASC;

    ELSIF V_CODIGOOPERACION = '0706' THEN
        OPEN CURSOR_ FOR
            SELECT
                p.CODIGO AS PRODUCTO,
                o.NUMEROOPERACION AS NUMEROOPERACION,
                o.CODIGOREPORTE ,
                c.CODIGO AS CLIENTE,
                c.NOMBRE,
                c.TIPODOCUMENTO,
                o.TIPOCLIENTE,
                '' AS  VALIDACION,
                o.FECHAREPORTE AS CONTRATACION,
                o.FECHATERMINO AS VENCIMIENTO,
                o.IMPORTEUSD,
                '' AS ESTADO

            FROM OPERACION_DERIVADO o
                INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
                INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
                INNER JOIN DIVISA d ON d.ID = o.IDDIVISA
            WHERE
                o.CODIGOESTADO = 1
                AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA, 'dd/mm/yyyy'))
                --QUITO LAS VENCIDAS
                AND TO_DATE(TO_CHAR(o.FECHATERMINO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHA, 'dd/mm/yyyy'))
                AND o.TIPOPROCESO = 'D'
                AND o.ID_PRODUCTO IN (SELECT p.ID FROM PRODUCTO p WHERE p.CODIGO IN ('ODIV'))
                AND c.CODIGO NOT IN ('PER013597')
                ORDER BY o.NUMEROOPERACION, o.CODIGOREPORTE ASC;

    ELSIF V_CODIGOOPERACION = '0799' THEN
        OPEN CURSOR_ FOR
            SELECT
                p.CODIGO AS PRODUCTO,
                o.NUMEROOPERACION AS NUMEROOPERACION,
                o.CODIGOREPORTE ,
                c.CODIGO AS CLIENTE,
                c.NOMBRE,
                c.TIPODOCUMENTO,
                o.TIPOCLIENTE,
                '' AS VALIDACION,
                o.FECHAREPORTE AS CONTRATACION,
                o.FECHATERMINO AS VENCIMIENTO,
                o.IMPORTEUSD,
                '' AS ESTADO
            FROM OPERACION_DERIVADO o
                INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
                INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
                INNER JOIN DIVISA d ON d.ID = o.IDDIVISA
            WHERE
                o.CODIGOESTADO = 1
                AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHA, 'dd/mm/yyyy'))
                --QUITO LAS VENCIDAS
                AND TO_DATE(TO_CHAR(o.FECHATERMINO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHA, 'dd/mm/yyyy'))
                AND o.TIPOPROCESO = 'D'
                AND o.ID_PRODUCTO IN (SELECT p.ID FROM PRODUCTO p WHERE p.CODIGO IN ('OTO'))
                ORDER BY o.NUMEROOPERACION, o.CODIGOREPORTE ASC;
    END IF;
END;
/
GRANT EXECUTE ON "PCBCRP"."SP_BCR_REPORTE4_OPERACIONES" TO "APP_PCBCRP";
GRANT EXECUTE ON "PCBCRP"."SP_BCR_REPORTE4_ANEXO8_IRC" TO "APP_PCBCRP";
GRANT EXECUTE ON "PCBCRP"."SP_BCR_REPORTE4_ANEXO8" TO "APP_PCBCRP";
GRANT EXECUTE ON "PCBCRP"."SP_BCR_REPORTE8_ANEXO8" TO "APP_PCBCRP";
GRANT EXECUTE ON "PCBCRP"."SP_BCR_REPORTE8_OPERACIONES" TO "APP_PCBCRP";
-- FIN SEBASTIAN