INSERT INTO PCBCRP.PARAMETRO(ID, CODIGO, DESCRIPCION, CODIGOESTADO) VALUES ('45', '045', 'Ruta Carpeta Star Altamira', 1);
INSERT INTO PCBCRP.PARAMETRO(ID, CODIGO, DESCRIPCION, CODIGOESTADO) VALUES ('46', '046', 'Nombre Archivo Star Altamira', 1);
INSERT INTO PCBCRP.PARAMETRO(ID, CODIGO, DESCRIPCION, CODIGOESTADO) VALUES ('47', '047', 'Hora Tarea Programada', 1);
INSERT INTO PCBCRP.PARAMETRO(ID, CODIGO, DESCRIPCION, CODIGOESTADO) VALUES ('48', '048', 'Cred. Servicio Interfaz Cliente', 1);
INSERT INTO PCBCRP.DETALLE_PARAMETRO (ID, CODIGO, DESCRIPCION, VISIBLE, ID_PARAMETRO, CODIGOESTADO) VALUES (SYS_GUID(), '001',	'Ruta Carpeta', '1', '45', 1);
INSERT INTO PCBCRP.DETALLE_PARAMETRO (ID, CODIGO, DESCRIPCION, VISIBLE, ID_PARAMETRO, CODIGOESTADO) VALUES (SYS_GUID(), '001',	'Nombre Archivo', '1', '46', 1);
INSERT INTO PCBCRP.DETALLE_PARAMETRO (ID, CODIGO, DESCRIPCION, VISIBLE, ID_PARAMETRO, CODIGOESTADO) VALUES (SYS_GUID(), '001',	'Expresion Cron', '1', '47', 1);
INSERT INTO PCBCRP.DETALLE_PARAMETRO (ID, CODIGO, DESCRIPCION, VISIBLE, ID_PARAMETRO, CODIGOESTADO) VALUES (SYS_GUID(), '001',	'Cred. Servicio Interfaz Cliente', '1', '48', 1);
INSERT INTO PCBCRP.VALOR_PARAMETRO (ID, VALOR,  ID_DETALLE, ORDEN, CODIGOESTADO) VALUES (SYS_GUID(), '/mnt/compartido/pcbcrp', (SELECT ID FROM PCBCRP.DETALLE_PARAMETRO WHERE CODIGO = '001' AND ID_PARAMETRO = '45'), 1, 1);
INSERT INTO PCBCRP.VALOR_PARAMETRO (ID, VALOR,  ID_DETALLE, ORDEN, CODIGOESTADO) VALUES (SYS_GUID(), 'REP_CONTRAPARTIDAS.csv', (SELECT ID FROM PCBCRP.DETALLE_PARAMETRO WHERE CODIGO = '001' AND ID_PARAMETRO = '46'), 1, 1);
INSERT INTO PCBCRP.VALOR_PARAMETRO (ID, VALOR,  ID_DETALLE, ORDEN, CODIGOESTADO) VALUES (SYS_GUID(), '0 00 20 * * ? *', (SELECT ID FROM PCBCRP.DETALLE_PARAMETRO WHERE CODIGO = '001' AND ID_PARAMETRO = '47'), 1, 1);
INSERT INTO PCBCRP.VALOR_PARAMETRO (ID, VALOR,  ID_DETALLE, ORDEN, CODIGOESTADO) VALUES (SYS_GUID(), 'P014303', (SELECT ID FROM PCBCRP.DETALLE_PARAMETRO WHERE CODIGO = '001' AND ID_PARAMETRO = '48'), 1, 1);
INSERT INTO PCBCRP.VALOR_PARAMETRO (ID, VALOR,  ID_DETALLE, ORDEN, CODIGOESTADO) VALUES (SYS_GUID(), 'Lima1502', (SELECT ID FROM PCBCRP.DETALLE_PARAMETRO WHERE CODIGO = '001' AND ID_PARAMETRO = '48'), 2, 1)