create or replace PROCEDURE          "SP_BCR_TASAS_UNWIND" (

P_IDCARGA 							IN VARCHAR2,
P_FECHACONTRATACION 				IN DATE,
P_IDPRODUCTO 						IN VARCHAR2,
P_NUMEROOPERACION 					IN VARCHAR2,
P_IDCLIENTE 						IN VARCHAR2,
P_TIPOOPERACION         			IN VARCHAR2,
P_IDDIVISAENTRADA 					IN VARCHAR2,
P_IDDIVISASALIDA 					IN VARCHAR2,
P_IMPORTEDIVISAENTRADA 				IN NUMBER,
P_IMPORTEDIVISASALIDA 				IN NUMBER,
P_COTIZACION 						IN NUMBER,
P_PUNTOSSWAP 						IN NUMBER,
P_BASICA 							IN VARCHAR2,
P_CAMBIOREF 						IN NUMBER,
P_FECHAVALOR 						IN DATE,
P_FECHAVENCIMIENTO 					IN DATE,
P_PLAZO 							IN NUMBER,
P_FECHAEJERCICIO 					IN DATE,
P_CALLPUT 							IN VARCHAR2,
P_PLAZA 							IN VARCHAR2,
P_PAISRESIDENCIA 					IN VARCHAR2,
P_RIESGOPAIS 						IN VARCHAR2,
P_PRIMA 							IN NUMBER,
P_IDDIVISAPRIMA 					IN VARCHAR2,
P_OBSERVACIONES 					IN VARCHAR2,
P_FECHAALTA 						IN DATE,
P_FECHAMODIFICACIONCARGA 			IN DATE,
P_OPERACIONSUSTITUYE 				IN VARCHAR2,
P_FECHABAJA 						IN DATE,
P_NIF 								IN VARCHAR2,
P_INTERMEDIARIO 					IN VARCHAR2,
P_INTERMEDIARIODESCRIPCION 			IN VARCHAR2,
P_ESTADO 							IN VARCHAR2,
P_CONTRATO 							IN VARCHAR2,
P_RESIDENTE 						IN VARCHAR2,
P_ESTILO 							IN VARCHAR2,
P_TIPOOPCION 						IN VARCHAR2,
P_TIPOPROCESO 						IN VARCHAR2,
P_HISTORICO 						IN NUMBER,
P_FECHAMOVIMIENTO 					IN DATE,
P_USUARIOCARGA 						IN VARCHAR2,
P_CODIGOOPERACION 					IN VARCHAR2,
P_IMPORTEUSD 						IN NUMBER,
P_CODIGOREPORTE 					IN VARCHAR2,
P_TASAMONEDANACIONAL 				IN NUMBER,
P_MONTOMONEDAEXTRAJERA 				IN NUMBER,
P_TASADIFERENCIAL 					IN NUMBER,
P_DELTA 							IN NUMBER,
P_TASAMONEDAEXTRANJERA 				IN NUMBER,
P_IDMONEDAEXTRANJERA 				IN VARCHAR2,
P_MONTOPEN 							IN NUMBER,
P_TIPOCAMBIOSPOT 					IN NUMBER,
P_TIPOCAMBIOPACTADO 				IN NUMBER,
P_TIPOCAMBIOVENCIMIENTO 			IN NUMBER,
P_VALIDACION 						IN VARCHAR2,
P_CODIGOAGRUPACION 					IN VARCHAR2,
P_TIPOCLIENTE 						IN VARCHAR2,
P_IDFILAARCHIVO 					IN NUMBER,

P_TIPOCARGA 						IN NUMBER,
P_TIPOACCION 						IN VARCHAR2,
P_USUARIOCREACION 					IN VARCHAR2,
P_INTENCIONCONTRATACION				IN VARCHAR2,
P_PAGAIDENTIFICFRECUENCIA		    IN VARCHAR2,
P_PAGATASAFIJASPREAD				IN NUMBER,
P_PAGATFIJA							IN VARCHAR2,
P_RECIBEIDENTIFICFRECUENCIA		    IN VARCHAR2,
P_RECIBETASAFIJASPREAD				IN NUMBER,
P_RECIBETFIJA						IN VARCHAR2

)

AS

V_IDTEMP                    VARCHAR2(255) := '';
V_CORRELATIVO				VARCHAR2(12) := '';
V_NUMEROOPERACION 			VARCHAR2(20);
V_HISTORICO					NUMBER;
V_COUNT 					NUMBER;
V_CODIGOESTADO 				NUMBER;
V_TASAMONEDANACIONAL 		NUMBER;
V_TASAMONEDAEXTRANJERA 		NUMBER;
V_MSG_EXCEP   		    	EXCEPTION;
V_ERROR                     VARCHAR2(500) := '';
V_CODPRODUCTO				VARCHAR2(20);

BEGIN
	SELECT pro.CODIGO INTO V_CODPRODUCTO FROM PRODUCTO pro WHERE pro.ID = P_IDPRODUCTO;

	IF (P_TIPOCARGA = 7 AND P_ESTADO != 'A') THEN -- identificador IRC
		V_NUMEROOPERACION := FN_BCR_TASAINTERES_GENERAIRD(V_CODPRODUCTO, P_NUMEROOPERACION);
		V_HISTORICO := 0;
	ELSE
		V_NUMEROOPERACION := P_NUMEROOPERACION;

		-- obtenemos el ultimo valor historico
		SELECT MAX(HISTORICO) INTO V_HISTORICO
		FROM TASA_INTERES
		WHERE NUMEROOPERACION = V_NUMEROOPERACION AND TIPOPROCESO = P_TIPOPROCESO;
	END IF;


	-- verificamos si ya existe un registro para la operacion Inforeport
	IF NVL(V_HISTORICO, 0) =  0 THEN
		V_HISTORICO := 1;
	ELSE
		--Obttenmos el estado del ultimo historico
		SELECT CODIGOESTADO INTO V_CODIGOESTADO
		FROM TASA_INTERES
		WHERE
			NUMEROOPERACION = V_NUMEROOPERACION
			AND HISTORICO = V_HISTORICO
			AND TIPOPROCESO = P_TIPOPROCESO;

		--Si el ultimo historico a sido eliminado
		IF V_CODIGOESTADO = 2 THEN -- Eliminado
			V_HISTORICO := V_HISTORICO + 1;
		ELSE
			-- verificamos si hay algun cambio en el ultimo registro
			SELECT
				COUNT(HISTORICO) INTO V_COUNT
			FROM
				TASA_INTERES
			WHERE
				(
					TO_CHAR(FECHACONTRATACION, 'dd/mm/yyyy')  <> TO_CHAR(P_FECHACONTRATACION, 'dd/mm/yyyy')
					OR ID_PRODUCTO <> P_IDPRODUCTO
					OR NUMEROOPERACION <> V_NUMEROOPERACION
					OR ID_CLIENTE <> P_IDCLIENTE
					OR TIPOOPERACION <> P_TIPOOPERACION
					OR IDDIVISAENTRADA <> P_IDDIVISAENTRADA
					OR IDDIVISASALIDA <> P_IDDIVISASALIDA
					OR IMPORTEDIVISAENTRADA <> P_IMPORTEDIVISAENTRADA
					OR IMPORTEDIVISASALIDA <>  P_IMPORTEDIVISASALIDA
					OR COTIZACION <> P_COTIZACION
					OR PUNTOSSWAP <> P_PUNTOSSWAP
					OR BASICA <> P_BASICA
					OR CAMBIOREF <> P_CAMBIOREF
					OR TO_CHAR(FECHAVALOR, 'dd/mm/yyyy') <> TO_CHAR(P_FECHAVALOR, 'dd/mm/yyyy')
					OR TO_CHAR(FECHAVENCIMIENTO, 'dd/mm/yyyy') <> TO_CHAR(P_FECHAVENCIMIENTO, 'dd/mm/yyyy')
					OR PLAZO <> P_PLAZO
					OR TO_CHAR(FECHAEJERCICIO, 'dd/mm/yyyy')  <> TO_CHAR(P_FECHAEJERCICIO, 'dd/mm/yyyy')
					OR CALLPUT <> P_CALLPUT
					OR PLAZA <> P_PLAZA
					OR PAISRESIDENCIA <> P_PAISRESIDENCIA
					OR RIESGOPAIS <> P_RIESGOPAIS
					OR PRIMA <> P_PRIMA
					OR IDDIVISAPRIMA <> P_IDDIVISAPRIMA
					OR OBSERVACIONES <> P_OBSERVACIONES
					OR TO_CHAR(FECHAALTA, 'dd/mm/yyyy') <> TO_CHAR(P_FECHAALTA, 'dd/mm/yyyy')
					OR TO_CHAR(FECHAMODIFICACIONCARGA, 'dd/mm/yyyy') <> TO_CHAR(P_FECHAMODIFICACIONCARGA, 'dd/mm/yyyy')
					OR OPERACIONSUSTITUYE <> P_OPERACIONSUSTITUYE
					OR TO_CHAR(FECHABAJA, 'dd/mm/yyyy') <> TO_CHAR(P_FECHABAJA, 'dd/mm/yyyy')
					OR NIF <> P_NIF
					OR INTERMEDIARIO <> P_INTERMEDIARIO
					OR INTERMEDIARIODESCRIPCION <> P_INTERMEDIARIODESCRIPCION
					OR ESTADO <> P_ESTADO
					OR CONTRATO <> P_CONTRATO
					OR RESIDENTE <> P_RESIDENTE
					OR ESTILO <> P_ESTILO
					OR TIPOOPCION <> P_TIPOOPCION
					OR TO_CHAR(FECHAMOVIMIENTO, 'dd/mm/yyyy') <> TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy')
					OR USUARIOCARGA <> P_USUARIOCARGA
					OR CODIGOOPERACION <> P_CODIGOOPERACION
					OR IMPORTEUSD <> P_IMPORTEUSD
					OR CODIGOREPORTE <> P_CODIGOREPORTE
					OR TASAMONEDANACIONAL <> P_TASAMONEDANACIONAL
					OR MONTOMONEDAEXTRANJERA <> P_MONTOMONEDAEXTRAJERA
					OR TASADIFERENCIAL <> P_TASADIFERENCIAL
					OR DELTA <> P_DELTA
					OR TASAMONEDAEXTRANJERA <> P_TASAMONEDAEXTRANJERA
					OR IDMONEDAEXTRANJERA <> P_IDMONEDAEXTRANJERA
					OR MONTOPEN <> P_MONTOPEN
					OR TIPOCAMBIOSPOT <> P_TIPOCAMBIOSPOT
					OR TIPOCAMBIOPACTADO <> P_TIPOCAMBIOPACTADO
					OR TIPOCAMBIOVENCIMIENTO <> P_TIPOCAMBIOVENCIMIENTO
					OR VALIDACION <> P_VALIDACION
					OR TIPOCLIENTE <> P_TIPOCLIENTE
				)
				AND HISTORICO = V_HISTORICO
				AND NUMEROOPERACION = V_NUMEROOPERACION
				AND TIPOPROCESO = P_TIPOPROCESO;


				IF (V_COUNT > 0) THEN
					--Eliminamos en forma logica la operacion anterior del la misma fecha de movimiento
					UPDATE TASA_INTERES
					SET CODIGOESTADO = 2
					WHERE
						HISTORICO = V_HISTORICO
						AND NUMEROOPERACION = V_NUMEROOPERACION
						AND TIPOPROCESO = P_TIPOPROCESO
						AND TO_CHAR(FECHAMOVIMIENTO, 'dd/mm/yyyy') = TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy');

					V_HISTORICO := V_HISTORICO + 1;
					COMMIT;
				ELSE
                    V_HISTORICO := NULL;  --para evitar q inserte el mismo registro 2 veces ya no se inserta
					V_ERROR := 'Existe un registro idéntico para la operación ' || V_NUMEROOPERACION;
					RAISE_APPLICATION_ERROR(-20001, V_ERROR);
				END IF;
		END IF;
	END IF;





	IF NVL(V_HISTORICO, 0) !=  0 THEN
		SELECT
			NVL(TASAMONEDANACIONAL, 0), NVL(TASAMONEDAEXTRANJERA, 0) INTO V_TASAMONEDANACIONAL, V_TASAMONEDAEXTRANJERA
		FROM
			TASA_INTERES
		WHERE
			CORRELATIVO IN (SELECT MAX(op.CORRELATIVO) FROM TASA_INTERES op WHERE op.NUMEROOPERACION = V_NUMEROOPERACION);


		V_IDTEMP := SYS_GUID();
		V_IDTEMP := LOWER(SUBSTR(V_IDTEMP, 1, 8) || '-' || SUBSTR(V_IDTEMP, 9, 4) || '-' || SUBSTR(V_IDTEMP, 13, 4) || '-' || SUBSTR(V_IDTEMP, 17, 4) || '-' || SUBSTR(V_IDTEMP, 21));
		V_CORRELATIVO := FN_BCR_CORREL_GENCOMPUESTO('TasaInteres');


		INSERT INTO TASA_INTERES (
				ID,
				ID_CARGA,
				FECHACONTRATACION,
				ID_PRODUCTO,
				NUMEROOPERACION,
				ID_CLIENTE,
				TIPOOPERACION,
				IDDIVISAENTRADA,
				IDDIVISASALIDA,
				IMPORTEDIVISAENTRADA,
				IMPORTEDIVISASALIDA,
				COTIZACION,
				PUNTOSSWAP,
				BASICA,
				CAMBIOREF,
				FECHAVALOR,
				FECHAVENCIMIENTO,
				PLAZO,
				FECHAEJERCICIO,
				CALLPUT,
				PLAZA,
				PAISRESIDENCIA,
				RIESGOPAIS,
				PRIMA,
				IDDIVISAPRIMA,
				OBSERVACIONES,
				FECHAALTA,
				FECHAMODIFICACIONCARGA,
				OPERACIONSUSTITUYE,
				FECHABAJA,
				NIF,
				INTERMEDIARIO,
				INTERMEDIARIODESCRIPCION,
				ESTADO,
				CONTRATO,
				RESIDENTE,
				ESTILO,
				TIPOOPCION,
				TIPOPROCESO,
				HISTORICO,
				FECHAMOVIMIENTO,
				USUARIOCARGA,
				CODIGOOPERACION,
				IMPORTEUSD,
				CODIGOREPORTE,
				TASAMONEDANACIONAL,
				MONTOMONEDAEXTRANJERA,
				TASADIFERENCIAL,
				DELTA,
				TASAMONEDAEXTRANJERA,
				IDMONEDAEXTRANJERA,
				MONTOPEN,
				TIPOCAMBIOSPOT,
				TIPOCAMBIOPACTADO,
				TIPOCAMBIOVENCIMIENTO,
				VALIDACION,
				CODIGOAGRUPACION,
				TIPOCLIENTE,
				IDFILAARCHIVO,
				CREADO_POR,
				FECHA_CREACION,
				CODIGOESTADO,
                TIPOACCION,
				CORRELATIVO,
				INTENCIONCONTRATACION,
				PAGAIDENTIFICADORFRECUENCIA,
				PAGATASAFIJASPREAD,
				PAGATFIJA,
				RECIBEIDENTIFICADORFRECUENCIA,
				RECIBETASAFIJASPREAD,
				RECIBETFIJA
			) VALUES (
				V_IDTEMP,
				P_IDCARGA,
				P_FECHACONTRATACION,
				P_IDPRODUCTO,
				V_NUMEROOPERACION,
				P_IDCLIENTE,
				P_TIPOOPERACION,
				P_IDDIVISAENTRADA,
				P_IDDIVISASALIDA,
				P_IMPORTEDIVISAENTRADA,
				P_IMPORTEDIVISASALIDA,
				P_COTIZACION,
				P_PUNTOSSWAP,
				P_BASICA,
				P_CAMBIOREF,
				P_FECHAVALOR,
				P_FECHAVENCIMIENTO,
				P_PLAZO,
				P_FECHAEJERCICIO,
				P_CALLPUT,
				P_PLAZA,
				P_PAISRESIDENCIA,
				P_RIESGOPAIS,
				P_PRIMA,
				P_IDDIVISAPRIMA,
				P_OBSERVACIONES,
				P_FECHAALTA,
				P_FECHAMODIFICACIONCARGA,
				P_OPERACIONSUSTITUYE,
				P_FECHABAJA,
				P_NIF,
				P_INTERMEDIARIO,
				P_INTERMEDIARIODESCRIPCION,
				P_ESTADO,
				P_CONTRATO,
				P_RESIDENTE,
				P_ESTILO,
				P_TIPOOPCION,
				P_TIPOPROCESO,
				V_HISTORICO,
				P_FECHAMOVIMIENTO,
				P_USUARIOCARGA,
				P_CODIGOOPERACION,
				P_IMPORTEUSD,
				P_CODIGOREPORTE,
				P_TASAMONEDANACIONAL,
				P_MONTOMONEDAEXTRAJERA,
				P_TASADIFERENCIAL,
				P_DELTA,
				P_TASAMONEDAEXTRANJERA,
				P_IDMONEDAEXTRANJERA,
				P_MONTOPEN,
				P_TIPOCAMBIOSPOT,
				P_TIPOCAMBIOPACTADO,
				P_TIPOCAMBIOVENCIMIENTO,
				P_VALIDACION,
				P_CODIGOAGRUPACION,
				P_TIPOCLIENTE,
				P_IDFILAARCHIVO,
				P_USUARIOCREACION,
				SYSDATE,
				1, 		-- estado activo
                P_TIPOACCION,
				V_CORRELATIVO,
				P_INTENCIONCONTRATACION,
				P_PAGAIDENTIFICFRECUENCIA,
				P_PAGATASAFIJASPREAD,
				P_PAGATFIJA,
				P_RECIBEIDENTIFICFRECUENCIA,
				P_RECIBETASAFIJASPREAD,
				P_RECIBETFIJA
			);
	END IF;

END;

