create or replace PROCEDURE          "SP_BCR_REPORTE6_EXCEL_C2" (
P_FECHAMOVIMIENTO IN DATE,
P_TIPOPROCESO  IN VARCHAR2,
CURSOR_ OUT SYS_REFCURSOR
)
AS
BEGIN
 OPEN CURSOR_ FOR
  -- lista de operaciones
		SELECT
			p.CODIGO AS PRODUCTODESCRIPCION,
			o.NUMEROOPERACION,
            o.CODIGOREPORTE,
			c.CODIGO AS CLIENTECODIGO,
			c.NOMBRE AS CLIENTENOMBRE,
            (SELECT
					det.DESCRIPCION
				FROM
					PARAMETRO par
						INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
						INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '002'
				WHERE
					val.VALOR = o.TIPOOPERACION
			)  AS TIPOOPERACIONDESCRIPCION,
			de.CODIGO AS  DIVISAENTRADADESCRIPCION,
			ds.CODIGO AS  DIVISASALIDADESCRIPCION,
			o.IMPORTEDIVISAENTRADA,
			o.IMPORTEDIVISASALIDA,
            o.TIPOCAMBIOSPOT,
            o.VALIDACION,
            o.FECHAVENCIMIENTO,
              CASE
            WHEN TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy') = TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy') THEN
                'V'
            ELSE
                o.TIPOACCION
            END AS TIPOACCION,
            o.DELTA,
            o.TASAMONEDANACIONAL,
			o.TASAMONEDAEXTRANJERA,
            o.IMPORTEUSD
		FROM TASA_INTERES o
			INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
			INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
			INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
			INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
			LEFT JOIN DIVISA dp ON dp.ID = o.IDDIVISAPRIMA
			LEFT JOIN DIVISA dex ON dex.ID = o.IDMONEDAEXTRANJERA
		WHERE
			o.CODIGOESTADO = 1
            AND (TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy') = TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy')
            OR TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy') = TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy') )
            AND o.TIPOPROCESO = P_TIPOPROCESO
            --AND o.ID_PRODUCTO = (SELECT p.ID FROM PRODUCTO p WHERE p.CODIGO = 'IRD') --@i_idProductoIRD
            ORDER BY TO_NUMBER(O.CORRELATIVO);
END;
