create or replace PROCEDURE          "SP_BCR_TASAINT_GENCODREPIRD" (
P_FECHAPROCESO 			IN DATE,
P_TIPOPROCESO			IN VARCHAR2
)

AS

V_CODIGO		 		VARCHAR2(20);
V_CODIGOREPORTE 	    VARCHAR2(20);

-- Obtener las operaciones del Reporte1
CURSOR C_XLS IS

SELECT
	SUBSTR(ti.NUMEROOPERACION, 1, LENGTH(ti.NUMEROOPERACION) - 3) AS NUMEROOPERACION,
	ti.CODIGOOPERACION,
	ti.FECHACONTRATACION
FROM
	TASA_INTERES ti
		INNER JOIN PRODUCTO pro ON pro.ID = ti.ID_PRODUCTO
		INNER JOIN CLIENTE cli ON cli.ID = ti.ID_CLIENTE
		INNER JOIN DIVISA divent ON divent.ID = ti.IDDIVISAENTRADA
		INNER JOIN DIVISA divsal ON divsal.ID = ti.IDDIVISASALIDA

		INNER JOIN (SELECT
						det.DESCRIPCION,
                        val.VALOR
					FROM
						PARAMETRO par
							INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
							INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '004'
					) tipcli ON cli.TIPOCLIENTE = tipcli.VALOR     -- Tipo Cliente

WHERE
	ti.ESTADO <> 'A' --Anulada
	AND ti.CODIGOESTADO = 1
	AND TO_CHAR(ti.FECHAMOVIMIENTO, 'dd/mm/yyyy') = TO_CHAR(P_FECHAPROCESO, 'dd/mm/yyyy')
	AND ti.TIPOPROCESO = P_TIPOPROCESO
	AND ti.ID_PRODUCTO IN (SELECT ID FROM PRODUCTO WHERE CODIGO IN ('IRD', 'IRCM')) 
GROUP BY
	SUBSTR(ti.NUMEROOPERACION, 1, LENGTH(ti.NUMEROOPERACION) - 3), ti.CODIGOOPERACION, ti.FECHACONTRATACION
ORDER BY
   SUBSTR(ti.NUMEROOPERACION, 1, LENGTH(ti.NUMEROOPERACION) - 3);

V_XLS                  C_XLS%ROWTYPE;

BEGIN

    OPEN C_XLS;

	LOOP
		FETCH C_XLS INTO V_XLS;
		EXIT WHEN C_XLS%NOTFOUND;
		BEGIN
            --Limpiar Codigo de Reporte1 generados anteriormente
            UPDATE TASA_INTERES
            SET CODIGOREPORTE = ''
            WHERE
                SUBSTR(NUMEROOPERACION, 1, LENGTH(NUMEROOPERACION) - 3) = V_XLS.NUMEROOPERACION;
        END;

	END LOOP;
	COMMIT;
	CLOSE C_XLS;


	OPEN C_XLS;

	LOOP
		FETCH C_XLS INTO V_XLS;
		EXIT WHEN C_XLS%NOTFOUND;
		BEGIN

			SELECT NVL(MAX(TO_NUMBER(SUBSTR(ti.CODIGOREPORTE, 11, 6))), 0) + 1  INTO V_CODIGO
			FROM TASA_INTERES ti
			WHERE
				ti.ESTADO <> 'A' --Anulada
				AND ti.CODIGOESTADO = 1
				AND ti.CODIGOREPORTE is not null
				AND TO_CHAR(ti.FECHACONTRATACION, 'dd/mm/yyyy') = TO_CHAR(V_XLS.FECHACONTRATACION, 'dd/mm/yyyy')
				AND ti.TIPOPROCESO = P_TIPOPROCESO;

			V_CODIGOREPORTE := TO_CHAR(V_XLS.FECHACONTRATACION, 'yyyymmdd') || V_XLS.CODIGOOPERACION || LPAD(V_CODIGO, 6, '0');


			UPDATE TASA_INTERES
			SET CODIGOREPORTE = V_CODIGOREPORTE
			WHERE
				SUBSTR(NUMEROOPERACION, 1, LENGTH(NUMEROOPERACION) - 3) = V_XLS.NUMEROOPERACION;

		END;

	END LOOP;
	COMMIT;
	CLOSE C_XLS;

END;