create or replace PROCEDURE          "SP_BCR_MSD_CALCULOMONTOS" (
P_FECHAMOVIMIENTO IN DATE
)
AS
V_ULTIMAFECHA   DATE;
V_COUNT         INT;

V_HISTORICO 	NUMBER(20, 6) := 0;
V_IRD           NUMBER(20, 6) := 0;
V_IRD_ANULADAS  NUMBER(20, 6) := 0;
V_IRCM          NUMBER(20, 6) := 0;
V_IRCM_ANULADAS NUMBER(20, 6) := 0;
V_OTO           NUMBER(20, 6) := 0;
V_ODIV          NUMBER(20, 6) := 0;

--Saldos del dia
CURSOR  C_MSD_DELDIA IS
SELECT
	MSD.ID,
	MSD.MONTO,
	SD.CODIGOOPERACION
FROM
	MOVIMIENTO_SALDO_DERIVADOS MSD
		INNER JOIN SALDO_DERIVADOS SD ON MSD.ID_SALDODERIVADOS = SD.ID
WHERE
	TO_CHAR(MSD.FECHA,'dd/mm/yyyyy') = TO_CHAR(P_FECHAMOVIMIENTO,'dd/mm/yyyyy')
	AND MSD.CODIGOESTADO = 1;

BEGIN

    --Calculamos importes historicos quitando las operaciones vencidas
        --REPORTE 6 IRD
        SELECT
			NVL(SUM(NVL(o.IMPORTEUSD,0)),0) INTO V_IRD
        FROM
			TASA_INTERES o
				INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
				INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
				INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
				INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
				LEFT JOIN DIVISA dp ON dp.ID = o.IDDIVISAPRIMA
				LEFT JOIN DIVISA dex ON dex.ID = o.IDMONEDAEXTRANJERA
		WHERE
            o.ESTADO <> 'A' --Anulada
			AND o.CODIGOESTADO = 1
            AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy'))
            --QUITO LAS VENCIDAS
            AND TO_DATE(TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy'))
            AND o.TIPOPROCESO = 'D'
            AND o.ID_PRODUCTO = (SELECT p.ID FROM PRODUCTO p WHERE p.CODIGO = 'IRD')--@i_idProductoIRD
        ORDER BY
			TO_NUMBER(O.CORRELATIVO);


		SELECT
			NVL(SUM(NVL(o.IMPORTEUSD,0)),0) INTO V_IRD_ANULADAS
        FROM
			TASA_INTERES o
				INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
				INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
				INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
				INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
				LEFT JOIN DIVISA dp ON dp.ID = o.IDDIVISAPRIMA
				LEFT JOIN DIVISA dex ON dex.ID = o.IDMONEDAEXTRANJERA
		WHERE
            o.ESTADO = 'A' --Anulada
			AND o.CODIGOESTADO = 1
            AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy'))
            --QUITO LAS VENCIDAS
            AND TO_DATE(TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy'))
            AND o.TIPOPROCESO = 'D'
            AND o.ID_PRODUCTO = (SELECT p.ID FROM PRODUCTO p WHERE p.CODIGO = 'IRD')--@i_idProductoIRD
        ORDER BY
			TO_NUMBER(O.CORRELATIVO);
			
		--REPORTE 6 IRCM
		SELECT
			NVL(SUM(NVL(o.IMPORTEUSD,0)),0) INTO V_IRCM
        FROM
			TASA_INTERES o
				INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
				INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
				INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
				INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
				LEFT JOIN DIVISA dp ON dp.ID = o.IDDIVISAPRIMA
				LEFT JOIN DIVISA dex ON dex.ID = o.IDMONEDAEXTRANJERA
		WHERE
            o.ESTADO <> 'A' --Anulada
			AND o.CODIGOESTADO = 1
            AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy'))
            --QUITO LAS VENCIDAS
            AND TO_DATE(TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy'))
            AND o.TIPOPROCESO = 'D'
            AND o.ID_PRODUCTO = (SELECT p.ID FROM PRODUCTO p WHERE p.CODIGO = 'IRCM')--@i_idProductoIRCM
        ORDER BY
			TO_NUMBER(O.CORRELATIVO);


		SELECT
			NVL(SUM(NVL(o.IMPORTEUSD,0)),0) INTO V_IRCM_ANULADAS
        FROM
			TASA_INTERES o
				INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
				INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
				INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
				INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
				LEFT JOIN DIVISA dp ON dp.ID = o.IDDIVISAPRIMA
				LEFT JOIN DIVISA dex ON dex.ID = o.IDMONEDAEXTRANJERA
		WHERE
            o.ESTADO = 'A' --Anulada
			AND o.CODIGOESTADO = 1
            AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy'))
            --QUITO LAS VENCIDAS
            AND TO_DATE(TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy'))
            AND o.TIPOPROCESO = 'D'
            AND o.ID_PRODUCTO = (SELECT p.ID FROM PRODUCTO p WHERE p.CODIGO = 'IRCM')--@i_idProductoIRCM
        ORDER BY
			TO_NUMBER(O.CORRELATIVO);


        --REPORTE 7 OTO
        SELECT
			NVL(SUM(NVL(o.IMPORTEUSD,0)),0) INTO V_OTO
		FROM
			OPERACION_DERIVADO o
				INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
				INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
				INNER JOIN DIVISA d ON d.ID = o.IDDIVISA
		WHERE
            o.CODIGOESTADO = 1
            AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy'))
            --QUITO LAS VENCIDAS
            AND TO_DATE(TO_CHAR(o.FECHATERMINO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy'))
            AND o.TIPOPROCESO = 'D'
            AND o.ID_PRODUCTO IN (SELECT p.ID FROM PRODUCTO p WHERE p.CODIGO IN ('OTO'))
        ORDER BY
			TO_NUMBER(O.CORRELATIVO);

        --REPORTE 7 ODIV
        SELECT
			NVL(SUM(NVL(o.IMPORTEUSD,0)),0) INTO V_ODIV
		FROM
			OPERACION_DERIVADO o
				INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
				INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
				INNER JOIN DIVISA d ON d.ID = o.IDDIVISA
		WHERE
            o.CODIGOESTADO = 1
            AND TO_DATE(TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy'))
            --QUITO LAS VENCIDAS
            AND TO_DATE(TO_CHAR(o.FECHATERMINO, 'dd/mm/yyyy')) > TO_DATE(TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy'))
            AND o.TIPOPROCESO = 'D'
            AND o.ID_PRODUCTO IN (SELECT p.ID FROM PRODUCTO p WHERE p.CODIGO IN ('ODIV'))
            AND c.CODIGO NOT IN ('PER013597')
        ORDER BY
			TO_NUMBER(O.CORRELATIVO);

    --Agregamos los importes

        FOR C_MSD IN C_MSD_DELDIA LOOP
            --Actualizo Historico
            IF C_MSD.CODIGOOPERACION = '0603' THEN
                UPDATE MOVIMIENTO_SALDO_DERIVADOS SET MONTO = V_IRD - V_IRD_ANULADAS
                WHERE ID = C_MSD.ID;
                COMMIT;
			ELSIF C_MSD.CODIGOOPERACION = '0604' THEN
                UPDATE MOVIMIENTO_SALDO_DERIVADOS SET MONTO = V_IRCM - V_IRCM_ANULADAS
                WHERE ID = C_MSD.ID;
                COMMIT;	
            ELSIF C_MSD.CODIGOOPERACION = '0706' THEN
                UPDATE MOVIMIENTO_SALDO_DERIVADOS SET MONTO = V_ODIV
                WHERE ID = C_MSD.ID;
                COMMIT;
            ELSIF C_MSD.CODIGOOPERACION = '0799' THEN
                UPDATE MOVIMIENTO_SALDO_DERIVADOS SET MONTO = V_OTO
                WHERE ID = C_MSD.ID;
                COMMIT;
            END IF;

        END LOOP;



    --SUMAMOS TOTALES
        FOR C_MSD  IN C_MSD_DELDIA LOOP
            --Actualizo Totales
            IF C_MSD.CODIGOOPERACION = '0600' THEN
                UPDATE MOVIMIENTO_SALDO_DERIVADOS
                SET MONTO = (
								SELECT
									SUM(MSD.MONTO)
								FROM
									MOVIMIENTO_SALDO_DERIVADOS MSD
										INNER JOIN SALDO_DERIVADOS SD ON MSD.ID_SALDODERIVADOS = SD.ID
								WHERE
									TO_CHAR(MSD.FECHA,'dd/mm/yyyyy') = TO_CHAR(P_FECHAMOVIMIENTO,'dd/mm/yyyyy')
									AND SD.CODIGOOPERACION IN ('0601','0602','0603','0604','0605','0606','0607','0608','0609','0610','0699')
									AND MSD.CODIGOESTADO = 1
                    )
                WHERE
					ID = C_MSD.ID;
                COMMIT;
            ELSIF C_MSD.CODIGOOPERACION = '0700' THEN
                UPDATE MOVIMIENTO_SALDO_DERIVADOS
                SET MONTO = (
								SELECT
									SUM(MSD.MONTO)
								FROM
									MOVIMIENTO_SALDO_DERIVADOS MSD
										INNER JOIN SALDO_DERIVADOS SD ON MSD.ID_SALDODERIVADOS = SD.ID
								WHERE
									TO_CHAR(MSD.FECHA,'dd/mm/yyyyy') = TO_CHAR(P_FECHAMOVIMIENTO,'dd/mm/yyyyy')
									AND SD.CODIGOOPERACION IN ('0701','0702','0703','0704','0704','0706','0799')
									AND MSD.CODIGOESTADO = 1
                    )
                WHERE
					ID = C_MSD.ID;
                COMMIT;
            END IF;
        END LOOP;
END;
