create or replace PROCEDURE          "SP_BCR_REPORTE6_LISTAR_C2" (
P_FECHAMOVIMIENTO IN DATE,
P_TIPOPROCESO  IN VARCHAR2,
CURSOR_ OUT SYS_REFCURSOR
)
AS
BEGIN
 OPEN CURSOR_ FOR
  -- lista de operaciones
		SELECT
			o.ID,
			o.ID_CARGA AS IDCARGA,
			o.FECHACONTRATACION, -- pendiente FECHA_REPORTE
			o.ID_PRODUCTO AS IDPRODUCTO,
			p.CODIGO AS PRODUCTODESCRIPCION,
			o.NUMEROOPERACION,
			o.ID_CLIENTE AS IDCLIENTE,
			c.CODIGO AS CLIENTECODIGO,
			c.NOMBRE AS CLIENTENOMBRE,
            c.TIPODOCUMENTO,
            CASE
              WHEN c.TIPODOCUMENTO = 1 OR c.TIPODOCUMENTO = 2 OR c.TIPODOCUMENTO = 3 OR c.TIPODOCUMENTO = 4 OR c.TIPODOCUMENTO = 5 THEN c.NUMERODOCUMENTO
              WHEN c.TIPODOCUMENTO = 6 THEN c.CODIGOSWIFT
            END AS DOCUMENTOCLIENTE,
			c.SECTOR AS SECTORCLIENTE,
            c.PAISRESIDENCIA AS CLIENTEPAISRESIDENCIA,
			p.TIPOENTREGA,
			o.TIPOOPERACION,
            (SELECT
					det.DESCRIPCION
				FROM
					PARAMETRO par
						INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
						INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '002'
				WHERE
					val.VALOR = o.TIPOOPERACION
			)  AS TIPOOPERACIONDESCRIPCION,
			o.IDDIVISAENTRADA,
			de.CODIGO AS  DIVISAENTRADADESCRIPCION,
			o.IDDIVISASALIDA,
			ds.CODIGO AS  DIVISASALIDADESCRIPCION,
			o.IMPORTEDIVISAENTRADA,
			o.IMPORTEDIVISASALIDA,
			o.COTIZACION,
			o.PUNTOSSWAP,
			o.BASICA,
			o.CAMBIOREF,
			o.FECHAVALOR,
			o.FECHAVENCIMIENTO,
			o.PLAZO,
			o.FECHAEJERCICIO,
			o.CALLPUT,
			o.PLAZA,
			o.PAISRESIDENCIA,
			o.RIESGOPAIS,
			o.PRIMA,
			o.IDDIVISAPRIMA,
			dp.CODIGO AS  DIVISAPRIMADESCRIPCION,
			CASE
			WHEN TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy') = TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy') THEN
				''
			ELSE
				o.OBSERVACIONES
			END AS OBSERVACIONES,
			o.FECHAALTA,
			o.FECHAMODIFICACIONCARGA,
			o.OPERACIONSUSTITUYE,
			o.FECHABAJA,
			o.NIF,
			o.INTERMEDIARIO,
			o.INTERMEDIARIODESCRIPCION,
			o.ESTADO,
			o.CONTRATO,
			o.RESIDENTE,
			o.ESTILO,
			o.TIPOOPCION,
			o.TIPOPROCESO,
			o.HISTORICO,
			o.FECHAMOVIMIENTO,
			o.USUARIOCARGA,
			o.CODIGOOPERACION,
			o.IMPORTEUSD,
			o.CODIGOREPORTE,
			o.TASAMONEDANACIONAL,
			o.TASAMONEDAEXTRANJERA,
			o.DELTA,
			o.MONTOMONEDAEXTRANJERA,
			o.IDMONEDAEXTRANJERA,
			dex.CODIGO AS  MONEDAEXTRANJERADESCRIPCION,
			o.MONTOPEN,
			o.TIPOCAMBIOSPOT,
			o.TIPOCAMBIOPACTADO,
			o.TIPOCAMBIOVENCIMIENTO,
			o.VALIDACION,
			o.CODIGOAGRUPACION,
			o.TIPOCLIENTE ,
			(SELECT
					det.DESCRIPCION
				FROM
					PARAMETRO par
						INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
						INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '004'
				WHERE
					val.VALOR = c.TIPOCLIENTE
			) AS TIPOCLIENTEDESCRIPCION,
			o.TASADIFERENCIAL,
			o.IDFILAARCHIVO,
            o.MENSAJEERROR,
			o.CODIGOESTADO,
            o.RECIBETASAFIJASPREAD,
            o.RECIBETFIJA,
            o.RECIBEIDENTIFICADORFRECUENCIA,
            o.PAGATASAFIJASPREAD,
            o.PAGATFIJA,
            o.PAGAIDENTIFICADORFRECUENCIA,
            o.VOLATILIDAD,
            o.INTENCIONCONTRATACION,
            CASE
            WHEN TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy') = TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy') THEN
                'V'
            ELSE
                o.TIPOACCION
            END AS TIPOACCION,
            '' as STRIKERATE,
            '' as BENCHMARK,
            '' as FRECUENCIABENCHMARK
		FROM TASA_INTERES o
			INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
			INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
			INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
			INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
			LEFT JOIN DIVISA dp ON dp.ID = o.IDDIVISAPRIMA
			LEFT JOIN DIVISA dex ON dex.ID = o.IDMONEDAEXTRANJERA
		WHERE
            o.CODIGOESTADO = 1
            AND (TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy') = TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy')
            OR TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy') = TO_CHAR(P_FECHAMOVIMIENTO, 'dd/mm/yyyy') )
            AND o.TIPOPROCESO = P_TIPOPROCESO
            --AND o.ID_PRODUCTO = (SELECT p.ID FROM PRODUCTO p WHERE p.CODIGO = 'IRD') --@i_idProductoIRD
        ORDER BY TO_NUMBER(O.CORRELATIVO);

END;

