create or replace PROCEDURE          "SP_BCR_TASINT_UPDFECEFECT_IRD" (
P_FECHAPROCESO 			IN DATE,
P_TIPOPROCESO			IN VARCHAR2,
P_USUARIOMODIFICACION	IN VARCHAR2
)

AS

V_NROFILA 						NUMBER(25, 2) := 1;
V_FECHAVENCIMIENTOANTERIOR		DATE;

-- lista de nro de tasas de interes
CURSOR C_NUMEROOPERACIONES(V_FECHAPROCESO DATE, V_TIPOPROCESO VARCHAR2) IS

SELECT SUBSTR(NUMEROOPERACION, 1, LENGTH(NUMEROOPERACION) - 3) AS NUMEROOPERACION
FROM TASA_INTERES
WHERE
	TO_CHAR(FECHAMOVIMIENTO, 'dd/mm/yyyy') = TO_CHAR(V_FECHAPROCESO, 'dd/mm/yyyy')
    AND TIPOPROCESO = V_TIPOPROCESO
    AND ID_PRODUCTO IN (SELECT ID FROM PRODUCTO WHERE CODIGO IN ('IRD', 'IRCM'))
GROUP BY
     SUBSTR(NUMEROOPERACION, 1, LENGTH(NUMEROOPERACION) - 3);

V_NUMEROOPERACIONES		C_NUMEROOPERACIONES%ROWTYPE;



-- lista de tasas de interes
CURSOR C_OPERACIONES(V_FECHAPROCESO DATE, V_TIPOPROCESO VARCHAR2, V_NUMEROOPERACION VARCHAR2) IS

SELECT
	ti.ID,
	ti.NUMEROOPERACION,
	ti.FECHACONTRATACION,
	ti.FECHAMOVIMIENTO,
	ti.FECHAVALOR,
	ti.FECHAVENCIMIENTO,
	ti.TIPOPROCESO,
	ti.ESTADO
FROM
	TASA_INTERES ti
WHERE
	SUBSTR(ti.NUMEROOPERACION, 1, LENGTH(NUMEROOPERACION) - 3) = V_NUMEROOPERACION
	AND TO_CHAR(ti.FECHAMOVIMIENTO, 'dd/mm/yyyy') = TO_CHAR(V_FECHAPROCESO, 'dd/mm/yyyy')
	AND ti.TIPOPROCESO = V_TIPOPROCESO
GROUP BY
     ti.ID,
	 ti.NUMEROOPERACION,
	 ti.FECHACONTRATACION,
	 ti.FECHAMOVIMIENTO,
	 ti.FECHAVALOR,
	 ti.FECHAVENCIMIENTO,
	 ti.TIPOPROCESO,
	 ti.ESTADO
ORDER BY
	ti.FECHAVENCIMIENTO ASC;

V_OPERACIONES			C_OPERACIONES%ROWTYPE;

BEGIN

	OPEN C_NUMEROOPERACIONES(P_FECHAPROCESO, P_TIPOPROCESO);

	LOOP
		FETCH C_NUMEROOPERACIONES INTO V_NUMEROOPERACIONES;
		EXIT WHEN C_NUMEROOPERACIONES%NOTFOUND;
		BEGIN

			V_NROFILA := 1;

			OPEN C_OPERACIONES(P_FECHAPROCESO, P_TIPOPROCESO, V_NUMEROOPERACIONES.NUMEROOPERACION);

			LOOP
				FETCH C_OPERACIONES INTO V_OPERACIONES;
				EXIT WHEN C_OPERACIONES%NOTFOUND;
				BEGIN
					IF V_NROFILA = 1 THEN
						UPDATE TASA_INTERES
						SET
							FECHAVALOR 		= V_OPERACIONES.FECHACONTRATACION,
							ACTUALIZADO_POR = P_USUARIOMODIFICACION
						WHERE
							ID = V_OPERACIONES.ID;

						COMMIT;

					ELSE
						UPDATE TASA_INTERES
						SET
							FECHAVALOR 		= V_FECHAVENCIMIENTOANTERIOR,
							ACTUALIZADO_POR = P_USUARIOMODIFICACION
						WHERE
							ID = V_OPERACIONES.ID;

						COMMIT;

					END IF;

					V_NROFILA := V_NROFILA + 1;
					V_FECHAVENCIMIENTOANTERIOR := FN_BCR_OBTENER_SGTE_DIA_UTIL(V_OPERACIONES.FECHAVENCIMIENTO + 1);

				END;
			END LOOP;
			CLOSE C_OPERACIONES;

		END;

	END LOOP;
	CLOSE C_NUMEROOPERACIONES;

END;