-- INICIO SEBASTIAN

--------------------------------------------------------
--  DELETE STORED PROCEDURES
--------------------------------------------------------
DROP PROCEDURE "PCBCRP"."SP_BCR_MPC_DETSOBCOMSOBVEN";
--------------------------------------------------------
--  DDL for Procedure SP_BCR_ANEXO_OCHO_PARAMETROS
--------------------------------------------------------
create PROCEDURE  "PCBCRP"."SP_BCR_MPC_DETSOBCOMSOBVEN" (
P_FECHAPROCESO		IN DATE,
P_TIPOPROCESO		IN VARCHAR2,
P_TIPOPEDIDO		IN VARCHAR2 DEFAULT NULL
)
AS

V_ID				VARCHAR2(50);

V_COMPRAS_FUT 		NUMBER(25, 6) := 0;  	-- IDPRODUCTO: 1
V_VENTAS_FUT 		NUMBER(25, 6) := 0;

V_COMPRAS_FXC 		NUMBER(25, 6) := 0;		-- IDPRODUCTO: 2
V_VENTAS_FXC 		NUMBER(25, 6) := 0;

V_COMPRAS_FXP 		NUMBER(25, 6) := 0;		-- IDPRODUCTO: 3
V_VENTAS_FXP 		NUMBER(25, 6) := 0;

V_COMPRAS_IND 		NUMBER(25, 6) := 0;		-- IDPRODUCTO: 4
V_VENTAS_IND 		NUMBER(25, 6) := 0;

V_COMPRAS_IRC 		NUMBER(25, 6) := 0;		-- IDPRODUCTO: 5
V_VENTAS_IRC 		NUMBER(25, 6) := 0;

V_COMPRAS_OTFX 		NUMBER(25, 6) := 0;		-- IDPRODUCTO: 7
V_VENTAS_OTFX 		NUMBER(25, 6) := 0;

V_DIFERENCIAL 		NUMBER(25, 6) := 0;


CURSOR C_PRODUCTOS IS
SELECT ID, CODIGO
FROM PRODUCTO
WHERE CODIGOESTADO = 1;

V_PRODUCTOS        			C_PRODUCTOS%ROWTYPE;


--PACTADAS -- REPORTE1
CURSOR C_OPERACIONESPACTADAS(V_FECHAPROCESO DATE, V_TIPOPROCESO VARCHAR2) IS

SELECT
	o.ID,
	o.ID_CARGA AS IDCARGA,
	o.FECHACONTRATACION,
	o.ID_PRODUCTO AS IDPRODUCTO,
	p.CODIGO AS PRODUCTODESCRIPCION,
	o.NUMEROOPERACION,
	o.ID_CLIENTE AS IDCLIENTE,
	c.CODIGO AS CLIENTECODIGO,
	c.NOMBRE AS CLIENTENOMBRE,
	c.SECTOR AS SECTORCLIENTE,
	c.PAISRESIDENCIA AS CLIENTEPAISRESIDENCIA,
	p.TIPOENTREGA,
	o.TIPOOPERACION,
	(	SELECT
			det.DESCRIPCION
		FROM
			PARAMETRO par
				INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
				INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '002'
		WHERE
			val.VALOR = o.TIPOOPERACION
	)  AS TIPOOPERACIONDESCRIPCION,
	o.IDDIVISAENTRADA,
	de.CODIGO AS  DIVISAENTRADADESCRIPCION,
	o.IDDIVISASALIDA,
	ds.CODIGO AS  DIVISASALIDADESCRIPCION,
	o.IMPORTEDIVISAENTRADA,
	o.IMPORTEDIVISASALIDA,
	o.COTIZACION,
	o.PUNTOSSWAP,
	o.BASICA,
	o.CAMBIOREF,
	o.FECHAVALOR,
	o.FECHAVENCIMIENTO,
	o.PLAZO,
	o.FECHAEJERCICIO,
	o.CALLPUT,
	o.PLAZA,
	o.PAISRESIDENCIA,
	o.RIESGOPAIS,
	o.PRIMA,
	o.IDDIVISAPRIMA,
	dp.CODIGO AS  DIVISAPRIMADESCRIPCION,
	o.OBSERVACIONES,
	o.FECHAALTA,
	o.FECHAMODIFICACIONCARGA,
	o.OPERACIONSUSTITUYE,
	o.FECHABAJA,
	o.NIF,
	o.INTERMEDIARIO,
	o.INTERMEDIARIODESCRIPCION,
	o.ESTADO,
	o.CONTRATO,
	o.RESIDENTE,
	o.ESTILO,
	o.TIPOOPCION,
	o.TIPOPROCESO,
	o.HISTORICO,
	o.FECHAMOVIMIENTO,
	o.USUARIOCARGA,
	o.CODIGOOPERACION,
	o.IMPORTEUSD,
	o.CODIGOREPORTE,
	o.TASAMONEDANACIONAL,
	o.TASAMONEDAEXTRANJERA,
	o.DELTA,
	o.MONTOMONEDAEXTRANJERA,
	o.IDMONEDAEXTRANJERA,
	dex.CODIGO AS  MONEDAEXTRANJERADESCRIPCION,
	o.MONTOPEN,
	o.TIPOCAMBIOSPOT,
	o.TIPOCAMBIOPACTADO,
	o.TIPOCAMBIOVENCIMIENTO,
	o.VALIDACION,
	o.CODIGOAGRUPACION,
	o.TIPOCLIENTE ,
	(	SELECT
			det.DESCRIPCION
		FROM
			PARAMETRO par
				INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
				INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '004'
		WHERE
			val.VALOR = o.TIPOCLIENTE
	) AS TIPOCLIENTEDESCRIPCION,
	o.TASADIFERENCIAL,
	o.IDFILAARCHIVO,
	o.CODIGOESTADO
FROM OPERACION o
	INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
	INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
	INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
	INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
	LEFT JOIN DIVISA dp ON dp.ID = o.IDDIVISAPRIMA
	LEFT JOIN DIVISA dex ON dex.ID = o.IDMONEDAEXTRANJERA
WHERE
	TO_CHAR(o.FECHACONTRATACION, 'dd/mm/yyyy') = TO_CHAR(o.FECHAMOVIMIENTO, 'dd/mm/yyyy')
	AND o.ESTADO <> 'A' --Anulada
	AND o.CODIGOESTADO = 1
	AND NVL(o.CODIGOAGRUPACION, 1) = 1 -- todas las operaciones que no se agrupan en menores a 500 mil
	AND TO_CHAR(o.FECHACONTRATACION, 'dd/mm/yyyy') = TO_CHAR(V_FECHAPROCESO, 'dd/mm/yyyy')
	AND  TRIM(o.TIPOPROCESO) = V_TIPOPROCESO
	AND concat(de.CODIGO, ds.CODIGO) LIKE '%' || (select d1.CODIGO from DIVISA d1 WHERE d1.ID = '11')  || '%'
ORDER BY TO_NUMBER(O.CORRELATIVO);

V_OPERACIONESPACTADAS       C_OPERACIONESPACTADAS%ROWTYPE;



--VENCIDAS --REPORTE2
CURSOR C_OPERACIONESVENCIDAS(V_FECHAPROCESO DATE, V_TIPOPROCESO VARCHAR2) IS
SELECT
	o.ID,
	o.ID_CARGA AS IDCARGA,
	o.FECHACONTRATACION,
	o.ID_PRODUCTO AS IDPRODUCTO,
	p.CODIGO AS PRODUCTODESCRIPCION,
	o.NUMEROOPERACION,
	o.ID_CLIENTE AS IDCLIENTE,
	c.CODIGO AS CLIENTECODIGO,
	c.NOMBRE AS CLIENTENOMBRE,
	c.SECTOR AS SECTORCLIENTE,
	c.PAISRESIDENCIA AS CLIENTEPAISRESIDENCIA,
	p.TIPOENTREGA,
	o.TIPOOPERACION,
	(	SELECT
			det.DESCRIPCION
		FROM
			PARAMETRO par
				INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
				INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '002'
		WHERE
			val.VALOR = o.TIPOOPERACION
	)  AS TIPOOPERACIONDESCRIPCION,
	o.IDDIVISAENTRADA,
	de.CODIGO AS  DIVISAENTRADADESCRIPCION,
	o.IDDIVISASALIDA,
	ds.CODIGO AS  DIVISASALIDADESCRIPCION,
	o.IMPORTEDIVISAENTRADA,
	o.IMPORTEDIVISASALIDA,
	o.COTIZACION,
	o.PUNTOSSWAP,
	o.BASICA,
	o.CAMBIOREF,
	o.FECHAVALOR,
	o.FECHAVENCIMIENTO,
	o.PLAZO,
	o.FECHAEJERCICIO,
	o.CALLPUT,
	o.PLAZA,
	o.PAISRESIDENCIA,
	o.RIESGOPAIS,
	o.PRIMA,
	o.IDDIVISAPRIMA,
	dp.CODIGO AS  DIVISAPRIMADESCRIPCION,
	o.OBSERVACIONES,
	o.FECHAALTA,
	o.FECHAMODIFICACIONCARGA,
	o.OPERACIONSUSTITUYE,
	o.FECHABAJA,
	o.NIF,
	o.INTERMEDIARIO,
	o.INTERMEDIARIODESCRIPCION,
	o.ESTADO,
	o.CONTRATO,
	o.RESIDENTE,
	o.ESTILO,
	o.TIPOOPCION,
	o.TIPOPROCESO,
	o.HISTORICO,
	o.FECHAMOVIMIENTO,
	o.USUARIOCARGA,
	o.CODIGOOPERACION,
	o.IMPORTEUSD,
	o.CODIGOREPORTE,
	o.TASAMONEDANACIONAL,
	o.TASAMONEDAEXTRANJERA,
	o.DELTA,
	o.MONTOMONEDAEXTRANJERA,
	o.IDMONEDAEXTRANJERA,
	dex.CODIGO AS  MONEDAEXTRANJERADESCRIPCION,
	o.MONTOPEN,
	o.TIPOCAMBIOSPOT,
	o.TIPOCAMBIOPACTADO,
	o.TIPOCAMBIOVENCIMIENTO,
	o.VALIDACION,
	o.CODIGOAGRUPACION,
	o.TIPOCLIENTE ,
	(	SELECT
			det.DESCRIPCION
		FROM
			PARAMETRO par
				INNER JOIN DETALLE_PARAMETRO det ON par.ID = det.ID_PARAMETRO
				INNER JOIN VALOR_PARAMETRO val ON det.ID = val.ID_DETALLE AND par.CODIGO = '004'
		WHERE
			val.VALOR = o.TIPOCLIENTE
	) AS TIPOCLIENTEDESCRIPCION,
	o.TASADIFERENCIAL,
	o.IDFILAARCHIVO,
	o.CODIGOESTADO
FROM OPERACION o
	INNER JOIN PRODUCTO p ON p.ID = o.ID_PRODUCTO
	INNER JOIN CLIENTE c ON c.ID = o.ID_CLIENTE
	INNER JOIN DIVISA de ON de.ID = o.IDDIVISAENTRADA
	INNER JOIN DIVISA ds ON ds.ID = o.IDDIVISASALIDA
	LEFT JOIN DIVISA dp ON dp.ID = o.IDDIVISAPRIMA
	LEFT JOIN DIVISA dex ON dex.ID = o.IDMONEDAEXTRANJERA
WHERE
	o.ESTADO <> 'A' --Anulada
	AND o.CODIGOESTADO = 1
	AND TO_CHAR(o.FECHAVENCIMIENTO, 'dd/mm/yyyy')= TO_CHAR(V_FECHAPROCESO, 'dd/mm/yyyy')
	AND  TRIM(o.TIPOPROCESO) = V_TIPOPROCESO
	AND concat(de.CODIGO, ds.CODIGO) LIKE '%' || (select d1.CODIGO from DIVISA d1 WHERE d1.ID = '11')  || '%'
	AND o.ID_PRODUCTO <> '2'
	AND NUMEROOPERACION NOT IN (
								SELECT os.NUMEROOPERACION FROM OPERACION os
								WHERE os.ESTADO = 'A'
								AND TO_DATE(TO_CHAR(os.FECHAMOVIMIENTO, 'dd/mm/yyyy')) <= TO_DATE(TO_CHAR(V_FECHAPROCESO, 'dd/mm/yyyy'))
								AND os.TIPOPROCESO = 'D')
ORDER BY TO_NUMBER(O.CORRELATIVO);

V_OPERACIONESVENCIDAS       C_OPERACIONESVENCIDAS%ROWTYPE;

BEGIN

	OPEN C_PRODUCTOS;

	LOOP
		FETCH C_PRODUCTOS INTO V_PRODUCTOS;
		EXIT WHEN C_PRODUCTOS%NOTFOUND;
		BEGIN

			IF V_PRODUCTOS.ID = '2' THEN
				OPEN C_OPERACIONESPACTADAS(P_FECHAPROCESO, P_TIPOPROCESO);

				LOOP
					FETCH C_OPERACIONESPACTADAS INTO V_OPERACIONESPACTADAS;
					EXIT WHEN C_OPERACIONESPACTADAS%NOTFOUND;
					BEGIN
						IF V_OPERACIONESPACTADAS.IDPRODUCTO != '8' AND V_OPERACIONESPACTADAS.IDPRODUCTO = V_PRODUCTOS.ID THEN      /*Cambio 15042014*/

							IF V_OPERACIONESPACTADAS.TIPOOPERACION = 'C' THEN
								V_COMPRAS_FXC := V_COMPRAS_FXC + V_OPERACIONESPACTADAS.IMPORTEUSD;
							END IF;

							IF V_OPERACIONESPACTADAS.TIPOOPERACION = 'V' THEN
								V_VENTAS_FXC := V_VENTAS_FXC + V_OPERACIONESPACTADAS.IMPORTEUSD;
							END IF;

						END IF;
					END;
				END LOOP;
				CLOSE C_OPERACIONESPACTADAS;

			END IF;


			IF V_PRODUCTOS.ID != '2' AND V_PRODUCTOS.ID != '6' THEN
				OPEN C_OPERACIONESVENCIDAS(P_FECHAPROCESO, P_TIPOPROCESO);

				LOOP
					FETCH C_OPERACIONESVENCIDAS INTO V_OPERACIONESVENCIDAS;
					EXIT WHEN C_OPERACIONESVENCIDAS%NOTFOUND;
					BEGIN
						IF V_OPERACIONESVENCIDAS.IDPRODUCTO != '8' AND V_OPERACIONESVENCIDAS.IDPRODUCTO = V_PRODUCTOS.ID THEN       /*Cambio 15042014*/

							IF V_OPERACIONESVENCIDAS.TIPOOPERACION = 'C' THEN
								CASE
									WHEN V_OPERACIONESVENCIDAS.IDPRODUCTO = '1' THEN V_COMPRAS_FUT := V_COMPRAS_FUT + V_OPERACIONESVENCIDAS.IMPORTEUSD;
									WHEN V_OPERACIONESVENCIDAS.IDPRODUCTO = '3' THEN V_COMPRAS_FXP := V_COMPRAS_FXP + V_OPERACIONESVENCIDAS.IMPORTEUSD;
									WHEN V_OPERACIONESVENCIDAS.IDPRODUCTO = '4' THEN V_COMPRAS_IND := V_COMPRAS_IND + V_OPERACIONESVENCIDAS.IMPORTEUSD;
									WHEN V_OPERACIONESVENCIDAS.IDPRODUCTO = '5' THEN V_COMPRAS_IRC := V_COMPRAS_IRC + V_OPERACIONESVENCIDAS.IMPORTEUSD;
									WHEN V_OPERACIONESVENCIDAS.IDPRODUCTO = '7' THEN V_COMPRAS_OTFX := V_COMPRAS_OTFX + V_OPERACIONESVENCIDAS.IMPORTEUSD;
								END CASE;

							END IF;

							IF V_OPERACIONESVENCIDAS.TIPOOPERACION = 'V' THEN
								CASE
									WHEN V_OPERACIONESVENCIDAS.IDPRODUCTO = '1' THEN V_VENTAS_FUT := V_VENTAS_FUT + V_OPERACIONESVENCIDAS.IMPORTEUSD;
									WHEN V_OPERACIONESVENCIDAS.IDPRODUCTO = '3' THEN V_VENTAS_FXP := V_VENTAS_FXP + V_OPERACIONESVENCIDAS.IMPORTEUSD;
									WHEN V_OPERACIONESVENCIDAS.IDPRODUCTO = '4' THEN V_VENTAS_IND := V_VENTAS_IND + V_OPERACIONESVENCIDAS.IMPORTEUSD;
									WHEN V_OPERACIONESVENCIDAS.IDPRODUCTO = '5' THEN V_VENTAS_IRC := V_VENTAS_IRC + V_OPERACIONESVENCIDAS.IMPORTEUSD;
									WHEN V_OPERACIONESVENCIDAS.IDPRODUCTO = '7' THEN V_VENTAS_OTFX := V_VENTAS_OTFX + V_OPERACIONESVENCIDAS.IMPORTEUSD;
								END CASE;

							END IF;

						END IF;
					END;
				END LOOP;
				CLOSE C_OPERACIONESVENCIDAS;

			END IF;

		END;
	END LOOP;
	CLOSE C_PRODUCTOS;
    
	IF NVL(P_TIPOPEDIDO, 'X') = 'X' THEN
		--TOTALES
		V_DIFERENCIAL := (ROUND(V_COMPRAS_FUT,2) + ROUND(V_COMPRAS_FXC,2) + ROUND(V_COMPRAS_FXP,2) +ROUND( V_COMPRAS_IND,2) + ROUND(V_COMPRAS_IRC,2) + ROUND(V_COMPRAS_OTFX,2)) - (ROUND(V_VENTAS_FUT,2) + ROUND(V_VENTAS_FXC,2) + ROUND(V_VENTAS_FXP,2) + ROUND(V_VENTAS_IND,2) + ROUND(V_VENTAS_IRC,2) + ROUND(V_VENTAS_OTFX,2));
	ELSE

		SELECT ID INTO V_ID
		FROM POSICION_CAMBIARIA
		WHERE CODIGO = '00200000';

		UPDATE MOVIMIENTO_POSICION_CAMBIARIA
		SET IMPORTEACTUAL =(ROUND(V_COMPRAS_FUT,2) + ROUND(V_COMPRAS_FXC,2) + ROUND(V_COMPRAS_FXP,2) + ROUND(V_COMPRAS_IND,2) + ROUND(V_COMPRAS_IRC,2) + ROUND(V_COMPRAS_OTFX,2)) - (ROUND(V_VENTAS_FUT,2) + ROUND(V_VENTAS_FXC,2) + ROUND(V_VENTAS_FXP,2) + ROUND(V_VENTAS_IND,2) + ROUND(V_VENTAS_IRC,2) + ROUND(V_VENTAS_OTFX,2))
		WHERE
			ID_POSICIONCAMBIARIA = V_ID --Sobrecompra o sobreventa del dÃ¯Â¿Â¿a
			AND TO_CHAR(FECHA, 'dd/mm/yyyy') = TO_CHAR(P_FECHAPROCESO, 'dd/mm/yyyy')
			AND  TRIM(TIPOPROCESO) = P_TIPOPROCESO;

	END IF;

END;
/
GRANT EXECUTE ON "PCBCRP"."SP_BCR_MPC_DETSOBCOMSOBVEN" TO "APP_PCBCRP";

-- fin SEBASTIAN