
package pe.grupobbva.alcon.core.ws.transacciones;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransaccionesSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransaccionesSoap {


    /**
     * 
     * @param strIdLogin
     * @param strSesion
     * @param strAmbienteHOST
     * @param strIpCliente
     * @param strPassword
     * @param strCodigoSistema
     * @param strUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidarUsuario", action = "http://tempuri.org/ValidarUsuario")
    @WebResult(name = "ValidarUsuarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidarUsuario", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidarUsuario")
    @ResponseWrapper(localName = "ValidarUsuarioResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidarUsuarioResponse")
    public String validarUsuario(
        @WebParam(name = "strIdLogin", targetNamespace = "http://tempuri.org/")
        String strIdLogin,
        @WebParam(name = "strAmbienteHOST", targetNamespace = "http://tempuri.org/")
        String strAmbienteHOST,
        @WebParam(name = "strIpCliente", targetNamespace = "http://tempuri.org/")
        String strIpCliente,
        @WebParam(name = "strSesion", targetNamespace = "http://tempuri.org/")
        String strSesion,
        @WebParam(name = "strUsuario", targetNamespace = "http://tempuri.org/")
        String strUsuario,
        @WebParam(name = "strPassword", targetNamespace = "http://tempuri.org/")
        String strPassword,
        @WebParam(name = "strCodigoSistema", targetNamespace = "http://tempuri.org/")
        String strCodigoSistema);

    /**
     * 
     * @param strIdLogin
     * @param strSesion
     * @param strAmbienteHOST
     * @param strIpCliente
     * @param strPassword
     * @param strCodigoSistema
     * @param strUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidarUsuarioPorTipo", action = "http://tempuri.org/ValidarUsuarioPorTipo")
    @WebResult(name = "ValidarUsuarioPorTipoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidarUsuarioPorTipo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidarUsuarioPorTipo")
    @ResponseWrapper(localName = "ValidarUsuarioPorTipoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidarUsuarioPorTipoResponse")
    public String validarUsuarioPorTipo(
        @WebParam(name = "strIdLogin", targetNamespace = "http://tempuri.org/")
        String strIdLogin,
        @WebParam(name = "strAmbienteHOST", targetNamespace = "http://tempuri.org/")
        String strAmbienteHOST,
        @WebParam(name = "strIpCliente", targetNamespace = "http://tempuri.org/")
        String strIpCliente,
        @WebParam(name = "strSesion", targetNamespace = "http://tempuri.org/")
        String strSesion,
        @WebParam(name = "strUsuario", targetNamespace = "http://tempuri.org/")
        String strUsuario,
        @WebParam(name = "strPassword", targetNamespace = "http://tempuri.org/")
        String strPassword,
        @WebParam(name = "strCodigoSistema", targetNamespace = "http://tempuri.org/")
        String strCodigoSistema);

    /**
     * 
     * @param strIdLogin
     * @param strSesion
     * @param strAmbienteHOST
     * @param strIpCliente
     * @param strPassword
     * @param strCodigoSistema
     * @param strUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListaMenu", action = "http://tempuri.org/ListaMenu")
    @WebResult(name = "ListaMenuResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListaMenu", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaMenu")
    @ResponseWrapper(localName = "ListaMenuResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaMenuResponse")
    public String listaMenu(
        @WebParam(name = "strIdLogin", targetNamespace = "http://tempuri.org/")
        String strIdLogin,
        @WebParam(name = "strAmbienteHOST", targetNamespace = "http://tempuri.org/")
        String strAmbienteHOST,
        @WebParam(name = "strIpCliente", targetNamespace = "http://tempuri.org/")
        String strIpCliente,
        @WebParam(name = "strSesion", targetNamespace = "http://tempuri.org/")
        String strSesion,
        @WebParam(name = "strUsuario", targetNamespace = "http://tempuri.org/")
        String strUsuario,
        @WebParam(name = "strPassword", targetNamespace = "http://tempuri.org/")
        String strPassword,
        @WebParam(name = "strCodigoSistema", targetNamespace = "http://tempuri.org/")
        String strCodigoSistema);

    /**
     * 
     * @param strIdLogin
     * @param strSesion
     * @param strAmbienteHOST
     * @param strIpCliente
     * @param strPassword
     * @param strCodigoSistema
     * @param sIdTrama
     * @param strUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListaMenuGenerico", action = "http://tempuri.org/ListaMenuGenerico")
    @WebResult(name = "ListaMenuGenericoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListaMenuGenerico", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaMenuGenerico")
    @ResponseWrapper(localName = "ListaMenuGenericoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaMenuGenericoResponse")
    public String listaMenuGenerico(
        @WebParam(name = "strIdLogin", targetNamespace = "http://tempuri.org/")
        String strIdLogin,
        @WebParam(name = "sIdTrama", targetNamespace = "http://tempuri.org/")
        String sIdTrama,
        @WebParam(name = "strAmbienteHOST", targetNamespace = "http://tempuri.org/")
        String strAmbienteHOST,
        @WebParam(name = "strIpCliente", targetNamespace = "http://tempuri.org/")
        String strIpCliente,
        @WebParam(name = "strSesion", targetNamespace = "http://tempuri.org/")
        String strSesion,
        @WebParam(name = "strUsuario", targetNamespace = "http://tempuri.org/")
        String strUsuario,
        @WebParam(name = "strPassword", targetNamespace = "http://tempuri.org/")
        String strPassword,
        @WebParam(name = "strCodigoSistema", targetNamespace = "http://tempuri.org/")
        String strCodigoSistema);

    /**
     * 
     * @param sTecla
     * @param strIdLogin
     * @param strSesion
     * @param strAmbienteHOST
     * @param strIpCliente
     * @param strPassword
     * @param strCodigoSistema
     * @param sIdTrama
     * @param strUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListaMenuGenericoSinTecla", action = "http://tempuri.org/ListaMenuGenericoSinTecla")
    @WebResult(name = "ListaMenuGenericoSinTeclaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListaMenuGenericoSinTecla", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaMenuGenericoSinTecla")
    @ResponseWrapper(localName = "ListaMenuGenericoSinTeclaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaMenuGenericoSinTeclaResponse")
    public String listaMenuGenericoSinTecla(
        @WebParam(name = "strIdLogin", targetNamespace = "http://tempuri.org/")
        String strIdLogin,
        @WebParam(name = "sIdTrama", targetNamespace = "http://tempuri.org/")
        String sIdTrama,
        @WebParam(name = "sTecla", targetNamespace = "http://tempuri.org/")
        String sTecla,
        @WebParam(name = "strAmbienteHOST", targetNamespace = "http://tempuri.org/")
        String strAmbienteHOST,
        @WebParam(name = "strIpCliente", targetNamespace = "http://tempuri.org/")
        String strIpCliente,
        @WebParam(name = "strSesion", targetNamespace = "http://tempuri.org/")
        String strSesion,
        @WebParam(name = "strUsuario", targetNamespace = "http://tempuri.org/")
        String strUsuario,
        @WebParam(name = "strPassword", targetNamespace = "http://tempuri.org/")
        String strPassword,
        @WebParam(name = "strCodigoSistema", targetNamespace = "http://tempuri.org/")
        String strCodigoSistema);

    /**
     * 
     * @param strTrama
     * @param strIdLogin
     * @param strSesion
     * @param strAmbienteHOST
     * @param strIpCliente
     * @param strIdTrama
     * @param strPassword
     * @param strCodigoSistema
     * @param strUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EnviaTramas", action = "http://tempuri.org/EnviaTramas")
    @WebResult(name = "EnviaTramasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EnviaTramas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviaTramas")
    @ResponseWrapper(localName = "EnviaTramasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviaTramasResponse")
    public String enviaTramas(
        @WebParam(name = "strIdLogin", targetNamespace = "http://tempuri.org/")
        String strIdLogin,
        @WebParam(name = "strIdTrama", targetNamespace = "http://tempuri.org/")
        String strIdTrama,
        @WebParam(name = "strTrama", targetNamespace = "http://tempuri.org/")
        String strTrama,
        @WebParam(name = "strAmbienteHOST", targetNamespace = "http://tempuri.org/")
        String strAmbienteHOST,
        @WebParam(name = "strIpCliente", targetNamespace = "http://tempuri.org/")
        String strIpCliente,
        @WebParam(name = "strSesion", targetNamespace = "http://tempuri.org/")
        String strSesion,
        @WebParam(name = "strUsuario", targetNamespace = "http://tempuri.org/")
        String strUsuario,
        @WebParam(name = "strPassword", targetNamespace = "http://tempuri.org/")
        String strPassword,
        @WebParam(name = "strCodigoSistema", targetNamespace = "http://tempuri.org/")
        String strCodigoSistema);

    /**
     * 
     * @param strTrama
     * @param strAmbienteHOST
     * @param strIpCliente
     * @param strIdTrama
     * @param strCodigoSistema
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SoloTrama", action = "http://tempuri.org/SoloTrama")
    @WebResult(name = "SoloTramaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SoloTrama", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SoloTrama")
    @ResponseWrapper(localName = "SoloTramaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SoloTramaResponse")
    public String soloTrama(
        @WebParam(name = "strIdTrama", targetNamespace = "http://tempuri.org/")
        String strIdTrama,
        @WebParam(name = "strTrama", targetNamespace = "http://tempuri.org/")
        String strTrama,
        @WebParam(name = "strAmbienteHOST", targetNamespace = "http://tempuri.org/")
        String strAmbienteHOST,
        @WebParam(name = "strIpCliente", targetNamespace = "http://tempuri.org/")
        String strIpCliente,
        @WebParam(name = "strCodigoSistema", targetNamespace = "http://tempuri.org/")
        String strCodigoSistema);

}
